// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/identity.dart';
import 'api/network.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 803012420;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'haven_core',
        ioDirectory: 'rust/haven_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<IdentityInfo> crateApiIdentityGenerateNewIdentity();

  Future<String?> crateApiNetworkGetLocalPeerId();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<List<StoredMessage>> crateApiStorageLoadMessages({
    required String peerId,
    required int limit,
  });

  Future<IdentityInfo> crateApiIdentityLoadOrCreateIdentity();

  Future<void> crateApiStorageOpenMessageStore();

  Future<NetworkEvent?> crateApiNetworkPollNetworkEvent();

  Future<IdentityInfo> crateApiIdentityRestoreIdentityFromMnemonic({
    required String phrase,
  });

  Future<PlatformInt64> crateApiStorageSaveMessage({
    required String peerId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  });

  Future<void> crateApiNetworkSendMessage({
    required String peerId,
    required String text,
  });

  Future<String> crateApiNetworkStartNode();

  Future<void> crateApiNetworkStopNode();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<IdentityInfo> crateApiIdentityGenerateNewIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateNewIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateNewIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_new_identity", argNames: []);

  @override
  Future<String?> crateApiNetworkGetLocalPeerId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetLocalPeerIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetLocalPeerIdConstMeta =>
      const TaskConstMeta(debugName: "get_local_peer_id", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<StoredMessage>> crateApiStorageLoadMessages({
    required String peerId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_stored_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageLoadMessagesConstMeta,
        argValues: [peerId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageLoadMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "load_messages",
        argNames: ["peerId", "limit"],
      );

  @override
  Future<IdentityInfo> crateApiIdentityLoadOrCreateIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityLoadOrCreateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityLoadOrCreateIdentityConstMeta =>
      const TaskConstMeta(debugName: "load_or_create_identity", argNames: []);

  @override
  Future<void> crateApiStorageOpenMessageStore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageOpenMessageStoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageOpenMessageStoreConstMeta =>
      const TaskConstMeta(debugName: "open_message_store", argNames: []);

  @override
  Future<NetworkEvent?> crateApiNetworkPollNetworkEvent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_network_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPollNetworkEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPollNetworkEventConstMeta =>
      const TaskConstMeta(debugName: "poll_network_event", argNames: []);

  @override
  Future<IdentityInfo> crateApiIdentityRestoreIdentityFromMnemonic({
    required String phrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityRestoreIdentityFromMnemonicConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityRestoreIdentityFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "restore_identity_from_mnemonic",
        argNames: ["phrase"],
      );

  @override
  Future<PlatformInt64> crateApiStorageSaveMessage({
    required String peerId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          sse_encode_bool(isMine, serializer);
          sse_encode_i_64(timestamp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageSaveMessageConstMeta,
        argValues: [peerId, text, isMine, timestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSaveMessageConstMeta => const TaskConstMeta(
    debugName: "save_message",
    argNames: ["peerId", "text", "isMine", "timestamp"],
  );

  @override
  Future<void> crateApiNetworkSendMessage({
    required String peerId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkSendMessageConstMeta,
        argValues: [peerId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["peerId", "text"],
  );

  @override
  Future<String> crateApiNetworkStartNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkStartNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStartNodeConstMeta =>
      const TaskConstMeta(debugName: "start_node", argNames: []);

  @override
  Future<void> crateApiNetworkStopNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkStopNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStopNodeConstMeta =>
      const TaskConstMeta(debugName: "stop_node", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiscoveredPeer dco_decode_box_autoadd_discovered_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_discovered_peer(raw);
  }

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_network_event(raw);
  }

  @protected
  DiscoveredPeer dco_decode_discovered_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiscoveredPeer(
      peerId: dco_decode_String(arr[0]),
      addresses: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      peerId: dco_decode_String(arr[0]),
      mnemonic: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stored_message).toList();
  }

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NetworkEvent_PeerDiscovered(
          peer: dco_decode_box_autoadd_discovered_peer(raw[1]),
        );
      case 1:
        return NetworkEvent_PeerExpired(peerId: dco_decode_String(raw[1]));
      case 2:
        return NetworkEvent_Listening(address: dco_decode_String(raw[1]));
      case 3:
        return NetworkEvent_MessageReceived(
          fromPeer: dco_decode_String(raw[1]),
          text: dco_decode_String(raw[2]),
        );
      case 4:
        return NetworkEvent_MessageSent(toPeer: dco_decode_String(raw[1]));
      case 5:
        return NetworkEvent_MessageSendFailed(
          toPeer: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 6:
        return NetworkEvent_Error(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NetworkEvent? dco_decode_opt_box_autoadd_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_network_event(raw);
  }

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StoredMessage(
      id: dco_decode_i_64(arr[0]),
      peerId: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      isMine: dco_decode_bool(arr[3]),
      timestamp: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiscoveredPeer sse_decode_box_autoadd_discovered_peer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_discovered_peer(deserializer));
  }

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_network_event(deserializer));
  }

  @protected
  DiscoveredPeer sse_decode_discovered_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    return DiscoveredPeer(peerId: var_peerId, addresses: var_addresses);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_mnemonic = sse_decode_opt_String(deserializer);
    return IdentityInfo(peerId: var_peerId, mnemonic: var_mnemonic);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_message(deserializer));
    }
    return ans_;
  }

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_peer = sse_decode_box_autoadd_discovered_peer(deserializer);
        return NetworkEvent_PeerDiscovered(peer: var_peer);
      case 1:
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_PeerExpired(peerId: var_peerId);
      case 2:
        var var_address = sse_decode_String(deserializer);
        return NetworkEvent_Listening(address: var_address);
      case 3:
        var var_fromPeer = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        return NetworkEvent_MessageReceived(
          fromPeer: var_fromPeer,
          text: var_text,
        );
      case 4:
        var var_toPeer = sse_decode_String(deserializer);
        return NetworkEvent_MessageSent(toPeer: var_toPeer);
      case 5:
        var var_toPeer = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return NetworkEvent_MessageSendFailed(
          toPeer: var_toPeer,
          error: var_error,
        );
      case 6:
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_Error(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NetworkEvent? sse_decode_opt_box_autoadd_network_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_network_event(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_peerId = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_isMine = sse_decode_bool(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return StoredMessage(
      id: var_id,
      peerId: var_peerId,
      text: var_text,
      isMine: var_isMine,
      timestamp: var_timestamp,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_discovered_peer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_network_event(
    NetworkEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_network_event(self, serializer);
  }

  @protected
  void sse_encode_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_list_String(self.addresses, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_opt_String(self.mnemonic, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_message(item, serializer);
    }
  }

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NetworkEvent_PeerDiscovered(peer: final peer):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_discovered_peer(peer, serializer);
      case NetworkEvent_PeerExpired(peerId: final peerId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_Listening(address: final address):
        sse_encode_i_32(2, serializer);
        sse_encode_String(address, serializer);
      case NetworkEvent_MessageReceived(
        fromPeer: final fromPeer,
        text: final text,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(fromPeer, serializer);
        sse_encode_String(text, serializer);
      case NetworkEvent_MessageSent(toPeer: final toPeer):
        sse_encode_i_32(4, serializer);
        sse_encode_String(toPeer, serializer);
      case NetworkEvent_MessageSendFailed(
        toPeer: final toPeer,
        error: final error,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(toPeer, serializer);
        sse_encode_String(error, serializer);
      case NetworkEvent_Error(message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_network_event(
    NetworkEvent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_network_event(self, serializer);
    }
  }

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.isMine, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
