// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crdt.dart';
import 'api/identity.dart';
import 'api/network.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2118436050;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'haven_core',
        ioDirectory: 'rust/haven_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCrdtChangeMemberRole({
    required String serverId,
    required String peerId,
    required String newRole,
  });

  Future<String> crateApiCrdtCreateChannel({
    required String serverId,
    required String name,
    String? category,
  });

  Future<String> crateApiCrdtCreateServer({required String name});

  Future<void> crateApiCrdtDeleteServer({required String serverId});

  Future<IdentityInfo> crateApiIdentityGenerateNewIdentity();

  Future<List<ServerFfi>> crateApiCrdtGetJoinedServers();

  Future<String?> crateApiNetworkGetLocalPeerId();

  Future<int> crateApiCrdtGetMyPermissions({required String serverId});

  Future<String> crateApiCrdtGetMyRole({required String serverId});

  Future<String?> crateApiNetworkGetOlmFingerprint();

  Future<List<ChannelFfi>> crateApiCrdtGetServerChannels({
    required String serverId,
  });

  Future<List<MemberFfi>> crateApiCrdtGetServerMembers({
    required String serverId,
  });

  Future<String> crateApiCrdtGetServerSetting({
    required String serverId,
    required String key,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiNetworkJoinRoom({required String roomCode});

  Future<void> crateApiCrdtJoinServer({required String serverId});

  Future<void> crateApiCrdtKickMember({
    required String serverId,
    required String peerId,
  });

  Future<List<StoredChannelMessage>> crateApiStorageLoadChannelMessages({
    required String serverId,
    required String channelId,
    required int limit,
  });

  Future<List<StoredMessage>> crateApiStorageLoadMessages({
    required String peerId,
    required int limit,
  });

  Future<IdentityInfo> crateApiIdentityLoadOrCreateIdentity();

  Future<void> crateApiNetworkNotifyShutdown();

  Future<void> crateApiStorageOpenMessageStore();

  Future<NetworkEvent?> crateApiNetworkPollNetworkEvent();

  Future<void> crateApiCrdtRemoveChannel({
    required String serverId,
    required String channelId,
  });

  Future<void> crateApiCrdtRenameChannel({
    required String serverId,
    required String channelId,
    required String newName,
  });

  Future<void> crateApiCrdtRenameServer({
    required String serverId,
    required String newName,
  });

  Future<void> crateApiNetworkRequestChannelSync({
    required String serverId,
    required String channelId,
  });

  Future<IdentityInfo> crateApiIdentityRestoreIdentityFromMnemonic({
    required String phrase,
  });

  Future<PlatformInt64> crateApiStorageSaveChannelMessage({
    required String serverId,
    required String channelId,
    required String senderId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  });

  Future<PlatformInt64> crateApiStorageSaveMessage({
    required String peerId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  });

  Future<void> crateApiNetworkSendChannelMessage({
    required String serverId,
    required String channelId,
    required String text,
  });

  Future<void> crateApiNetworkSendMessage({
    required String peerId,
    required String text,
  });

  Future<String> crateApiNetworkStartNode();

  Future<void> crateApiNetworkStopNode();

  Future<void> crateApiCrdtUpdateServerSetting({
    required String serverId,
    required String key,
    required String value,
  });

  Stream<NetworkEvent> crateApiNetworkWatchNetworkEvents();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCrdtChangeMemberRole({
    required String serverId,
    required String peerId,
    required String newRole,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(peerId, serializer);
          sse_encode_String(newRole, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtChangeMemberRoleConstMeta,
        argValues: [serverId, peerId, newRole],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtChangeMemberRoleConstMeta =>
      const TaskConstMeta(
        debugName: "change_member_role",
        argNames: ["serverId", "peerId", "newRole"],
      );

  @override
  Future<String> crateApiCrdtCreateChannel({
    required String serverId,
    required String name,
    String? category,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(category, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtCreateChannelConstMeta,
        argValues: [serverId, name, category],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtCreateChannelConstMeta => const TaskConstMeta(
    debugName: "create_channel",
    argNames: ["serverId", "name", "category"],
  );

  @override
  Future<String> crateApiCrdtCreateServer({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtCreateServerConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtCreateServerConstMeta =>
      const TaskConstMeta(debugName: "create_server", argNames: ["name"]);

  @override
  Future<void> crateApiCrdtDeleteServer({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtDeleteServerConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtDeleteServerConstMeta =>
      const TaskConstMeta(debugName: "delete_server", argNames: ["serverId"]);

  @override
  Future<IdentityInfo> crateApiIdentityGenerateNewIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateNewIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateNewIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_new_identity", argNames: []);

  @override
  Future<List<ServerFfi>> crateApiCrdtGetJoinedServers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_server_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetJoinedServersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetJoinedServersConstMeta =>
      const TaskConstMeta(debugName: "get_joined_servers", argNames: []);

  @override
  Future<String?> crateApiNetworkGetLocalPeerId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetLocalPeerIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetLocalPeerIdConstMeta =>
      const TaskConstMeta(debugName: "get_local_peer_id", argNames: []);

  @override
  Future<int> crateApiCrdtGetMyPermissions({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetMyPermissionsConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetMyPermissionsConstMeta =>
      const TaskConstMeta(
        debugName: "get_my_permissions",
        argNames: ["serverId"],
      );

  @override
  Future<String> crateApiCrdtGetMyRole({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetMyRoleConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetMyRoleConstMeta =>
      const TaskConstMeta(debugName: "get_my_role", argNames: ["serverId"]);

  @override
  Future<String?> crateApiNetworkGetOlmFingerprint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetOlmFingerprintConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetOlmFingerprintConstMeta =>
      const TaskConstMeta(debugName: "get_olm_fingerprint", argNames: []);

  @override
  Future<List<ChannelFfi>> crateApiCrdtGetServerChannels({
    required String serverId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_channel_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetServerChannelsConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetServerChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "get_server_channels",
        argNames: ["serverId"],
      );

  @override
  Future<List<MemberFfi>> crateApiCrdtGetServerMembers({
    required String serverId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_member_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetServerMembersConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetServerMembersConstMeta =>
      const TaskConstMeta(
        debugName: "get_server_members",
        argNames: ["serverId"],
      );

  @override
  Future<String> crateApiCrdtGetServerSetting({
    required String serverId,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtGetServerSettingConstMeta,
        argValues: [serverId, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtGetServerSettingConstMeta =>
      const TaskConstMeta(
        debugName: "get_server_setting",
        argNames: ["serverId", "key"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiNetworkJoinRoom({required String roomCode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkJoinRoomConstMeta,
        argValues: [roomCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkJoinRoomConstMeta =>
      const TaskConstMeta(debugName: "join_room", argNames: ["roomCode"]);

  @override
  Future<void> crateApiCrdtJoinServer({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtJoinServerConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtJoinServerConstMeta =>
      const TaskConstMeta(debugName: "join_server", argNames: ["serverId"]);

  @override
  Future<void> crateApiCrdtKickMember({
    required String serverId,
    required String peerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtKickMemberConstMeta,
        argValues: [serverId, peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtKickMemberConstMeta => const TaskConstMeta(
    debugName: "kick_member",
    argNames: ["serverId", "peerId"],
  );

  @override
  Future<List<StoredChannelMessage>> crateApiStorageLoadChannelMessages({
    required String serverId,
    required String channelId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          sse_encode_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_stored_channel_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageLoadChannelMessagesConstMeta,
        argValues: [serverId, channelId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageLoadChannelMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "load_channel_messages",
        argNames: ["serverId", "channelId", "limit"],
      );

  @override
  Future<List<StoredMessage>> crateApiStorageLoadMessages({
    required String peerId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_stored_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageLoadMessagesConstMeta,
        argValues: [peerId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageLoadMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "load_messages",
        argNames: ["peerId", "limit"],
      );

  @override
  Future<IdentityInfo> crateApiIdentityLoadOrCreateIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityLoadOrCreateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityLoadOrCreateIdentityConstMeta =>
      const TaskConstMeta(debugName: "load_or_create_identity", argNames: []);

  @override
  Future<void> crateApiNetworkNotifyShutdown() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkNotifyShutdownConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkNotifyShutdownConstMeta =>
      const TaskConstMeta(debugName: "notify_shutdown", argNames: []);

  @override
  Future<void> crateApiStorageOpenMessageStore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageOpenMessageStoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageOpenMessageStoreConstMeta =>
      const TaskConstMeta(debugName: "open_message_store", argNames: []);

  @override
  Future<NetworkEvent?> crateApiNetworkPollNetworkEvent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_network_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkPollNetworkEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkPollNetworkEventConstMeta =>
      const TaskConstMeta(debugName: "poll_network_event", argNames: []);

  @override
  Future<void> crateApiCrdtRemoveChannel({
    required String serverId,
    required String channelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtRemoveChannelConstMeta,
        argValues: [serverId, channelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtRemoveChannelConstMeta => const TaskConstMeta(
    debugName: "remove_channel",
    argNames: ["serverId", "channelId"],
  );

  @override
  Future<void> crateApiCrdtRenameChannel({
    required String serverId,
    required String channelId,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtRenameChannelConstMeta,
        argValues: [serverId, channelId, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtRenameChannelConstMeta => const TaskConstMeta(
    debugName: "rename_channel",
    argNames: ["serverId", "channelId", "newName"],
  );

  @override
  Future<void> crateApiCrdtRenameServer({
    required String serverId,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtRenameServerConstMeta,
        argValues: [serverId, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtRenameServerConstMeta => const TaskConstMeta(
    debugName: "rename_server",
    argNames: ["serverId", "newName"],
  );

  @override
  Future<void> crateApiNetworkRequestChannelSync({
    required String serverId,
    required String channelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkRequestChannelSyncConstMeta,
        argValues: [serverId, channelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkRequestChannelSyncConstMeta =>
      const TaskConstMeta(
        debugName: "request_channel_sync",
        argNames: ["serverId", "channelId"],
      );

  @override
  Future<IdentityInfo> crateApiIdentityRestoreIdentityFromMnemonic({
    required String phrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityRestoreIdentityFromMnemonicConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityRestoreIdentityFromMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "restore_identity_from_mnemonic",
        argNames: ["phrase"],
      );

  @override
  Future<PlatformInt64> crateApiStorageSaveChannelMessage({
    required String serverId,
    required String channelId,
    required String senderId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          sse_encode_String(senderId, serializer);
          sse_encode_String(text, serializer);
          sse_encode_bool(isMine, serializer);
          sse_encode_i_64(timestamp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageSaveChannelMessageConstMeta,
        argValues: [serverId, channelId, senderId, text, isMine, timestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSaveChannelMessageConstMeta =>
      const TaskConstMeta(
        debugName: "save_channel_message",
        argNames: [
          "serverId",
          "channelId",
          "senderId",
          "text",
          "isMine",
          "timestamp",
        ],
      );

  @override
  Future<PlatformInt64> crateApiStorageSaveMessage({
    required String peerId,
    required String text,
    required bool isMine,
    required PlatformInt64 timestamp,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          sse_encode_bool(isMine, serializer);
          sse_encode_i_64(timestamp, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStorageSaveMessageConstMeta,
        argValues: [peerId, text, isMine, timestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStorageSaveMessageConstMeta => const TaskConstMeta(
    debugName: "save_message",
    argNames: ["peerId", "text", "isMine", "timestamp"],
  );

  @override
  Future<void> crateApiNetworkSendChannelMessage({
    required String serverId,
    required String channelId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(channelId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkSendChannelMessageConstMeta,
        argValues: [serverId, channelId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSendChannelMessageConstMeta =>
      const TaskConstMeta(
        debugName: "send_channel_message",
        argNames: ["serverId", "channelId", "text"],
      );

  @override
  Future<void> crateApiNetworkSendMessage({
    required String peerId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkSendMessageConstMeta,
        argValues: [peerId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["peerId", "text"],
  );

  @override
  Future<String> crateApiNetworkStartNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkStartNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStartNodeConstMeta =>
      const TaskConstMeta(debugName: "start_node", argNames: []);

  @override
  Future<void> crateApiNetworkStopNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNetworkStopNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkStopNodeConstMeta =>
      const TaskConstMeta(debugName: "stop_node", argNames: []);

  @override
  Future<void> crateApiCrdtUpdateServerSetting({
    required String serverId,
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtUpdateServerSettingConstMeta,
        argValues: [serverId, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtUpdateServerSettingConstMeta =>
      const TaskConstMeta(
        debugName: "update_server_setting",
        argNames: ["serverId", "key", "value"],
      );

  @override
  Stream<NetworkEvent> crateApiNetworkWatchNetworkEvents() {
    final sink = RustStreamSink<NetworkEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_network_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 37,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNetworkWatchNetworkEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiNetworkWatchNetworkEventsConstMeta =>
      const TaskConstMeta(
        debugName: "watch_network_events",
        argNames: ["sink"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NetworkEvent> dco_decode_StreamSink_network_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DiscoveredPeer dco_decode_box_autoadd_discovered_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_discovered_peer(raw);
  }

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_network_event(raw);
  }

  @protected
  ChannelFfi dco_decode_channel_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChannelFfi(
      channelId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      category: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  DiscoveredPeer dco_decode_discovered_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiscoveredPeer(
      peerId: dco_decode_String(arr[0]),
      addresses: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IdentityInfo(
      peerId: dco_decode_String(arr[0]),
      mnemonic: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChannelFfi> dco_decode_list_channel_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel_ffi).toList();
  }

  @protected
  List<MemberFfi> dco_decode_list_member_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_ffi).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ServerFfi> dco_decode_list_server_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_server_ffi).toList();
  }

  @protected
  List<StoredChannelMessage> dco_decode_list_stored_channel_message(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_stored_channel_message)
        .toList();
  }

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stored_message).toList();
  }

  @protected
  MemberFfi dco_decode_member_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MemberFfi(
      peerId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
    );
  }

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NetworkEvent_PeerDiscovered(
          peer: dco_decode_box_autoadd_discovered_peer(raw[1]),
        );
      case 1:
        return NetworkEvent_PeerExpired(peerId: dco_decode_String(raw[1]));
      case 2:
        return NetworkEvent_PeerDisconnected(peerId: dco_decode_String(raw[1]));
      case 3:
        return NetworkEvent_RoomCleared();
      case 4:
        return NetworkEvent_Listening(address: dco_decode_String(raw[1]));
      case 5:
        return NetworkEvent_MessageReceived(
          fromPeer: dco_decode_String(raw[1]),
          text: dco_decode_String(raw[2]),
        );
      case 6:
        return NetworkEvent_ChannelMessageReceived(
          serverId: dco_decode_String(raw[1]),
          channelId: dco_decode_String(raw[2]),
          fromPeer: dco_decode_String(raw[3]),
          text: dco_decode_String(raw[4]),
          timestamp: dco_decode_i_64(raw[5]),
        );
      case 7:
        return NetworkEvent_MessageSent(toPeer: dco_decode_String(raw[1]));
      case 8:
        return NetworkEvent_MessageSendFailed(
          toPeer: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 9:
        return NetworkEvent_SessionEstablished(
          peerId: dco_decode_String(raw[1]),
        );
      case 10:
        return NetworkEvent_Error(message: dco_decode_String(raw[1]));
      case 11:
        return NetworkEvent_ServerCreated(
          serverId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 12:
        return NetworkEvent_ServerUpdated(serverId: dco_decode_String(raw[1]));
      case 13:
        return NetworkEvent_ChannelAdded(
          serverId: dco_decode_String(raw[1]),
          channelId: dco_decode_String(raw[2]),
          name: dco_decode_String(raw[3]),
        );
      case 14:
        return NetworkEvent_ChannelRemoved(
          serverId: dco_decode_String(raw[1]),
          channelId: dco_decode_String(raw[2]),
        );
      case 15:
        return NetworkEvent_ChannelRenamed(
          serverId: dco_decode_String(raw[1]),
          channelId: dco_decode_String(raw[2]),
          newName: dco_decode_String(raw[3]),
        );
      case 16:
        return NetworkEvent_ServerDeleted(serverId: dco_decode_String(raw[1]));
      case 17:
        return NetworkEvent_MemberJoined(
          serverId: dco_decode_String(raw[1]),
          peerId: dco_decode_String(raw[2]),
        );
      case 18:
        return NetworkEvent_MemberLeft(
          serverId: dco_decode_String(raw[1]),
          peerId: dco_decode_String(raw[2]),
        );
      case 19:
        return NetworkEvent_SyncCompleted(
          serverId: dco_decode_String(raw[1]),
          opsApplied: dco_decode_u_32(raw[2]),
        );
      case 20:
        return NetworkEvent_ServerJoined(
          serverId: dco_decode_String(raw[1]),
          name: dco_decode_String(raw[2]),
        );
      case 21:
        return NetworkEvent_MessageSyncStarted(
          serverId: dco_decode_String(raw[1]),
          peerId: dco_decode_String(raw[2]),
        );
      case 22:
        return NetworkEvent_MessageSyncCompleted(
          serverId: dco_decode_String(raw[1]),
          newMessageCount: dco_decode_u_32(raw[2]),
        );
      case 23:
        return NetworkEvent_MessageSyncFailed(
          serverId: dco_decode_String(raw[1]),
          error: dco_decode_String(raw[2]),
        );
      case 24:
        return NetworkEvent_MessageSyncProgress(
          serverId: dco_decode_String(raw[1]),
          channelId: dco_decode_String(raw[2]),
          receivedCount: dco_decode_u_32(raw[3]),
          totalCount: dco_decode_u_32(raw[4]),
        );
      case 25:
        return NetworkEvent_RoleChanged(
          serverId: dco_decode_String(raw[1]),
          peerId: dco_decode_String(raw[2]),
          newRole: dco_decode_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NetworkEvent? dco_decode_opt_box_autoadd_network_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_network_event(raw);
  }

  @protected
  ServerFfi dco_decode_server_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ServerFfi(
      serverId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      memberCount: dco_decode_u_32(arr[2]),
      channelCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  StoredChannelMessage dco_decode_stored_channel_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StoredChannelMessage(
      id: dco_decode_i_64(arr[0]),
      serverId: dco_decode_String(arr[1]),
      channelId: dco_decode_String(arr[2]),
      senderId: dco_decode_String(arr[3]),
      text: dco_decode_String(arr[4]),
      isMine: dco_decode_bool(arr[5]),
      timestamp: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StoredMessage(
      id: dco_decode_i_64(arr[0]),
      peerId: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      isMine: dco_decode_bool(arr[3]),
      timestamp: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NetworkEvent> sse_decode_StreamSink_network_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DiscoveredPeer sse_decode_box_autoadd_discovered_peer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_discovered_peer(deserializer));
  }

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_network_event(deserializer));
  }

  @protected
  ChannelFfi sse_decode_channel_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channelId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_category = sse_decode_opt_String(deserializer);
    return ChannelFfi(
      channelId: var_channelId,
      name: var_name,
      category: var_category,
    );
  }

  @protected
  DiscoveredPeer sse_decode_discovered_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_addresses = sse_decode_list_String(deserializer);
    return DiscoveredPeer(peerId: var_peerId, addresses: var_addresses);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_mnemonic = sse_decode_opt_String(deserializer);
    return IdentityInfo(peerId: var_peerId, mnemonic: var_mnemonic);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChannelFfi> sse_decode_list_channel_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChannelFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberFfi> sse_decode_list_member_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ServerFfi> sse_decode_list_server_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServerFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_server_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoredChannelMessage> sse_decode_list_stored_channel_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredChannelMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_channel_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoredMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stored_message(deserializer));
    }
    return ans_;
  }

  @protected
  MemberFfi sse_decode_member_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    return MemberFfi(
      peerId: var_peerId,
      displayName: var_displayName,
      role: var_role,
    );
  }

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_peer = sse_decode_box_autoadd_discovered_peer(deserializer);
        return NetworkEvent_PeerDiscovered(peer: var_peer);
      case 1:
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_PeerExpired(peerId: var_peerId);
      case 2:
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_PeerDisconnected(peerId: var_peerId);
      case 3:
        return NetworkEvent_RoomCleared();
      case 4:
        var var_address = sse_decode_String(deserializer);
        return NetworkEvent_Listening(address: var_address);
      case 5:
        var var_fromPeer = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        return NetworkEvent_MessageReceived(
          fromPeer: var_fromPeer,
          text: var_text,
        );
      case 6:
        var var_serverId = sse_decode_String(deserializer);
        var var_channelId = sse_decode_String(deserializer);
        var var_fromPeer = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        var var_timestamp = sse_decode_i_64(deserializer);
        return NetworkEvent_ChannelMessageReceived(
          serverId: var_serverId,
          channelId: var_channelId,
          fromPeer: var_fromPeer,
          text: var_text,
          timestamp: var_timestamp,
        );
      case 7:
        var var_toPeer = sse_decode_String(deserializer);
        return NetworkEvent_MessageSent(toPeer: var_toPeer);
      case 8:
        var var_toPeer = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return NetworkEvent_MessageSendFailed(
          toPeer: var_toPeer,
          error: var_error,
        );
      case 9:
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_SessionEstablished(peerId: var_peerId);
      case 10:
        var var_message = sse_decode_String(deserializer);
        return NetworkEvent_Error(message: var_message);
      case 11:
        var var_serverId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return NetworkEvent_ServerCreated(
          serverId: var_serverId,
          name: var_name,
        );
      case 12:
        var var_serverId = sse_decode_String(deserializer);
        return NetworkEvent_ServerUpdated(serverId: var_serverId);
      case 13:
        var var_serverId = sse_decode_String(deserializer);
        var var_channelId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return NetworkEvent_ChannelAdded(
          serverId: var_serverId,
          channelId: var_channelId,
          name: var_name,
        );
      case 14:
        var var_serverId = sse_decode_String(deserializer);
        var var_channelId = sse_decode_String(deserializer);
        return NetworkEvent_ChannelRemoved(
          serverId: var_serverId,
          channelId: var_channelId,
        );
      case 15:
        var var_serverId = sse_decode_String(deserializer);
        var var_channelId = sse_decode_String(deserializer);
        var var_newName = sse_decode_String(deserializer);
        return NetworkEvent_ChannelRenamed(
          serverId: var_serverId,
          channelId: var_channelId,
          newName: var_newName,
        );
      case 16:
        var var_serverId = sse_decode_String(deserializer);
        return NetworkEvent_ServerDeleted(serverId: var_serverId);
      case 17:
        var var_serverId = sse_decode_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_MemberJoined(
          serverId: var_serverId,
          peerId: var_peerId,
        );
      case 18:
        var var_serverId = sse_decode_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_MemberLeft(
          serverId: var_serverId,
          peerId: var_peerId,
        );
      case 19:
        var var_serverId = sse_decode_String(deserializer);
        var var_opsApplied = sse_decode_u_32(deserializer);
        return NetworkEvent_SyncCompleted(
          serverId: var_serverId,
          opsApplied: var_opsApplied,
        );
      case 20:
        var var_serverId = sse_decode_String(deserializer);
        var var_name = sse_decode_String(deserializer);
        return NetworkEvent_ServerJoined(
          serverId: var_serverId,
          name: var_name,
        );
      case 21:
        var var_serverId = sse_decode_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        return NetworkEvent_MessageSyncStarted(
          serverId: var_serverId,
          peerId: var_peerId,
        );
      case 22:
        var var_serverId = sse_decode_String(deserializer);
        var var_newMessageCount = sse_decode_u_32(deserializer);
        return NetworkEvent_MessageSyncCompleted(
          serverId: var_serverId,
          newMessageCount: var_newMessageCount,
        );
      case 23:
        var var_serverId = sse_decode_String(deserializer);
        var var_error = sse_decode_String(deserializer);
        return NetworkEvent_MessageSyncFailed(
          serverId: var_serverId,
          error: var_error,
        );
      case 24:
        var var_serverId = sse_decode_String(deserializer);
        var var_channelId = sse_decode_String(deserializer);
        var var_receivedCount = sse_decode_u_32(deserializer);
        var var_totalCount = sse_decode_u_32(deserializer);
        return NetworkEvent_MessageSyncProgress(
          serverId: var_serverId,
          channelId: var_channelId,
          receivedCount: var_receivedCount,
          totalCount: var_totalCount,
        );
      case 25:
        var var_serverId = sse_decode_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        var var_newRole = sse_decode_String(deserializer);
        return NetworkEvent_RoleChanged(
          serverId: var_serverId,
          peerId: var_peerId,
          newRole: var_newRole,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NetworkEvent? sse_decode_opt_box_autoadd_network_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_network_event(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ServerFfi sse_decode_server_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_memberCount = sse_decode_u_32(deserializer);
    var var_channelCount = sse_decode_u_32(deserializer);
    return ServerFfi(
      serverId: var_serverId,
      name: var_name,
      memberCount: var_memberCount,
      channelCount: var_channelCount,
    );
  }

  @protected
  StoredChannelMessage sse_decode_stored_channel_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_serverId = sse_decode_String(deserializer);
    var var_channelId = sse_decode_String(deserializer);
    var var_senderId = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_isMine = sse_decode_bool(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return StoredChannelMessage(
      id: var_id,
      serverId: var_serverId,
      channelId: var_channelId,
      senderId: var_senderId,
      text: var_text,
      isMine: var_isMine,
      timestamp: var_timestamp,
    );
  }

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_peerId = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_isMine = sse_decode_bool(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return StoredMessage(
      id: var_id,
      peerId: var_peerId,
      text: var_text,
      isMine: var_isMine,
      timestamp: var_timestamp,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_network_event_Sse(
    RustStreamSink<NetworkEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_discovered_peer(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_network_event(
    NetworkEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_network_event(self, serializer);
  }

  @protected
  void sse_encode_channel_ffi(ChannelFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.channelId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.category, serializer);
  }

  @protected
  void sse_encode_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_list_String(self.addresses, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_opt_String(self.mnemonic, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_channel_ffi(
    List<ChannelFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_ffi(
    List<MemberFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_server_ffi(
    List<ServerFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_server_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stored_channel_message(
    List<StoredChannelMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_channel_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stored_message(item, serializer);
    }
  }

  @protected
  void sse_encode_member_ffi(MemberFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.role, serializer);
  }

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NetworkEvent_PeerDiscovered(peer: final peer):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_discovered_peer(peer, serializer);
      case NetworkEvent_PeerExpired(peerId: final peerId):
        sse_encode_i_32(1, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_PeerDisconnected(peerId: final peerId):
        sse_encode_i_32(2, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_RoomCleared():
        sse_encode_i_32(3, serializer);
      case NetworkEvent_Listening(address: final address):
        sse_encode_i_32(4, serializer);
        sse_encode_String(address, serializer);
      case NetworkEvent_MessageReceived(
        fromPeer: final fromPeer,
        text: final text,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(fromPeer, serializer);
        sse_encode_String(text, serializer);
      case NetworkEvent_ChannelMessageReceived(
        serverId: final serverId,
        channelId: final channelId,
        fromPeer: final fromPeer,
        text: final text,
        timestamp: final timestamp,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(channelId, serializer);
        sse_encode_String(fromPeer, serializer);
        sse_encode_String(text, serializer);
        sse_encode_i_64(timestamp, serializer);
      case NetworkEvent_MessageSent(toPeer: final toPeer):
        sse_encode_i_32(7, serializer);
        sse_encode_String(toPeer, serializer);
      case NetworkEvent_MessageSendFailed(
        toPeer: final toPeer,
        error: final error,
      ):
        sse_encode_i_32(8, serializer);
        sse_encode_String(toPeer, serializer);
        sse_encode_String(error, serializer);
      case NetworkEvent_SessionEstablished(peerId: final peerId):
        sse_encode_i_32(9, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_Error(message: final message):
        sse_encode_i_32(10, serializer);
        sse_encode_String(message, serializer);
      case NetworkEvent_ServerCreated(
        serverId: final serverId,
        name: final name,
      ):
        sse_encode_i_32(11, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(name, serializer);
      case NetworkEvent_ServerUpdated(serverId: final serverId):
        sse_encode_i_32(12, serializer);
        sse_encode_String(serverId, serializer);
      case NetworkEvent_ChannelAdded(
        serverId: final serverId,
        channelId: final channelId,
        name: final name,
      ):
        sse_encode_i_32(13, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(channelId, serializer);
        sse_encode_String(name, serializer);
      case NetworkEvent_ChannelRemoved(
        serverId: final serverId,
        channelId: final channelId,
      ):
        sse_encode_i_32(14, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(channelId, serializer);
      case NetworkEvent_ChannelRenamed(
        serverId: final serverId,
        channelId: final channelId,
        newName: final newName,
      ):
        sse_encode_i_32(15, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(channelId, serializer);
        sse_encode_String(newName, serializer);
      case NetworkEvent_ServerDeleted(serverId: final serverId):
        sse_encode_i_32(16, serializer);
        sse_encode_String(serverId, serializer);
      case NetworkEvent_MemberJoined(
        serverId: final serverId,
        peerId: final peerId,
      ):
        sse_encode_i_32(17, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_MemberLeft(
        serverId: final serverId,
        peerId: final peerId,
      ):
        sse_encode_i_32(18, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_SyncCompleted(
        serverId: final serverId,
        opsApplied: final opsApplied,
      ):
        sse_encode_i_32(19, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_u_32(opsApplied, serializer);
      case NetworkEvent_ServerJoined(
        serverId: final serverId,
        name: final name,
      ):
        sse_encode_i_32(20, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(name, serializer);
      case NetworkEvent_MessageSyncStarted(
        serverId: final serverId,
        peerId: final peerId,
      ):
        sse_encode_i_32(21, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(peerId, serializer);
      case NetworkEvent_MessageSyncCompleted(
        serverId: final serverId,
        newMessageCount: final newMessageCount,
      ):
        sse_encode_i_32(22, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_u_32(newMessageCount, serializer);
      case NetworkEvent_MessageSyncFailed(
        serverId: final serverId,
        error: final error,
      ):
        sse_encode_i_32(23, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(error, serializer);
      case NetworkEvent_MessageSyncProgress(
        serverId: final serverId,
        channelId: final channelId,
        receivedCount: final receivedCount,
        totalCount: final totalCount,
      ):
        sse_encode_i_32(24, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(channelId, serializer);
        sse_encode_u_32(receivedCount, serializer);
        sse_encode_u_32(totalCount, serializer);
      case NetworkEvent_RoleChanged(
        serverId: final serverId,
        peerId: final peerId,
        newRole: final newRole,
      ):
        sse_encode_i_32(25, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(peerId, serializer);
        sse_encode_String(newRole, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_network_event(
    NetworkEvent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_network_event(self, serializer);
    }
  }

  @protected
  void sse_encode_server_ffi(ServerFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.memberCount, serializer);
    sse_encode_u_32(self.channelCount, serializer);
  }

  @protected
  void sse_encode_stored_channel_message(
    StoredChannelMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.serverId, serializer);
    sse_encode_String(self.channelId, serializer);
    sse_encode_String(self.senderId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.isMine, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.isMine, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
