// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/archive.dart';
import 'api/crdt.dart';
import 'api/identity.dart';
import 'api/network.dart';
import 'api/share.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'api/twitch.dart';
import 'api/updater.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadProgress> dco_decode_StreamSink_download_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetworkEvent> dco_decode_StreamSink_network_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArchiveChannelInfoFfi dco_decode_archive_channel_info_ffi(dynamic raw);

  @protected
  ArchiveData dco_decode_archive_data(dynamic raw);

  @protected
  ArchiveDeletionFfi dco_decode_archive_deletion_ffi(dynamic raw);

  @protected
  ArchiveEditFfi dco_decode_archive_edit_ffi(dynamic raw);

  @protected
  ArchiveFileFfi dco_decode_archive_file_ffi(dynamic raw);

  @protected
  ArchiveMessageFfi dco_decode_archive_message_ffi(dynamic raw);

  @protected
  ArchivePubKeyFfi dco_decode_archive_pub_key_ffi(dynamic raw);

  @protected
  ArchiveReactionFfi dco_decode_archive_reaction_ffi(dynamic raw);

  @protected
  ArchiveReactionRemovalFfi dco_decode_archive_reaction_removal_ffi(
    dynamic raw,
  );

  @protected
  ArchiveVerifyResult dco_decode_archive_verify_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_box_autoadd_discovered_peer(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LinkPreviewRef dco_decode_box_autoadd_link_preview_ref(dynamic raw);

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw);

  @protected
  StoredFileInfo dco_decode_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile dco_decode_box_autoadd_user_profile(dynamic raw);

  @protected
  VideoThumbRef dco_decode_box_autoadd_video_thumb_ref(dynamic raw);

  @protected
  ChannelFfi dco_decode_channel_ffi(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_discovered_peer(dynamic raw);

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FriendFfi dco_decode_friend_ffi(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw);

  @protected
  LabelFfi dco_decode_label_ffi(dynamic raw);

  @protected
  LinkPreviewRef dco_decode_link_preview_ref(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ArchiveChannelInfoFfi> dco_decode_list_archive_channel_info_ffi(
    dynamic raw,
  );

  @protected
  List<ArchiveDeletionFfi> dco_decode_list_archive_deletion_ffi(dynamic raw);

  @protected
  List<ArchiveEditFfi> dco_decode_list_archive_edit_ffi(dynamic raw);

  @protected
  List<ArchiveFileFfi> dco_decode_list_archive_file_ffi(dynamic raw);

  @protected
  List<ArchiveMessageFfi> dco_decode_list_archive_message_ffi(dynamic raw);

  @protected
  List<ArchivePubKeyFfi> dco_decode_list_archive_pub_key_ffi(dynamic raw);

  @protected
  List<ArchiveReactionFfi> dco_decode_list_archive_reaction_ffi(dynamic raw);

  @protected
  List<ArchiveReactionRemovalFfi> dco_decode_list_archive_reaction_removal_ffi(
    dynamic raw,
  );

  @protected
  List<ChannelFfi> dco_decode_list_channel_ffi(dynamic raw);

  @protected
  List<FriendFfi> dco_decode_list_friend_ffi(dynamic raw);

  @protected
  List<LabelFfi> dco_decode_list_label_ffi(dynamic raw);

  @protected
  List<MemberFfi> dco_decode_list_member_ffi(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, PlatformInt64)> dco_decode_list_record_string_i_64(dynamic raw);

  @protected
  List<ServerFfi> dco_decode_list_server_ffi(dynamic raw);

  @protected
  List<ShareEntry> dco_decode_list_share_entry(dynamic raw);

  @protected
  List<StoredChannelMessage> dco_decode_list_stored_channel_message(
    dynamic raw,
  );

  @protected
  List<StoredFileInfo> dco_decode_list_stored_file_info(dynamic raw);

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw);

  @protected
  List<StoredMessageEdit> dco_decode_list_stored_message_edit(dynamic raw);

  @protected
  List<StoredReaction> dco_decode_list_stored_reaction(dynamic raw);

  @protected
  List<UserProfile> dco_decode_list_user_profile(dynamic raw);

  @protected
  List<VaultFileStatusFfi> dco_decode_list_vault_file_status_ffi(dynamic raw);

  @protected
  MemberFfi dco_decode_member_ffi(dynamic raw);

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LinkPreviewRef? dco_decode_opt_box_autoadd_link_preview_ref(dynamic raw);

  @protected
  NetworkEvent? dco_decode_opt_box_autoadd_network_event(dynamic raw);

  @protected
  StoredFileInfo? dco_decode_opt_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile? dco_decode_opt_box_autoadd_user_profile(dynamic raw);

  @protected
  VideoThumbRef? dco_decode_opt_box_autoadd_video_thumb_ref(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (String, PlatformInt64) dco_decode_record_string_i_64(dynamic raw);

  @protected
  ServerFfi dco_decode_server_ffi(dynamic raw);

  @protected
  ShardImportResultFfi dco_decode_shard_import_result_ffi(dynamic raw);

  @protected
  ShareEntry dco_decode_share_entry(dynamic raw);

  @protected
  ShareLinkInfo dco_decode_share_link_info(dynamic raw);

  @protected
  StorageStatsFfi dco_decode_storage_stats_ffi(dynamic raw);

  @protected
  StoredChannelMessage dco_decode_stored_channel_message(dynamic raw);

  @protected
  StoredFileInfo dco_decode_stored_file_info(dynamic raw);

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw);

  @protected
  StoredMessageEdit dco_decode_stored_message_edit(dynamic raw);

  @protected
  StoredReaction dco_decode_stored_reaction(dynamic raw);

  @protected
  TwitchDeviceFlowResult dco_decode_twitch_device_flow_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultFileStatusFfi dco_decode_vault_file_status_ffi(dynamic raw);

  @protected
  VideoThumbRef dco_decode_video_thumb_ref(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadProgress> sse_decode_StreamSink_download_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetworkEvent> sse_decode_StreamSink_network_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveChannelInfoFfi sse_decode_archive_channel_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveData sse_decode_archive_data(SseDeserializer deserializer);

  @protected
  ArchiveDeletionFfi sse_decode_archive_deletion_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveEditFfi sse_decode_archive_edit_ffi(SseDeserializer deserializer);

  @protected
  ArchiveFileFfi sse_decode_archive_file_ffi(SseDeserializer deserializer);

  @protected
  ArchiveMessageFfi sse_decode_archive_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchivePubKeyFfi sse_decode_archive_pub_key_ffi(SseDeserializer deserializer);

  @protected
  ArchiveReactionFfi sse_decode_archive_reaction_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveReactionRemovalFfi sse_decode_archive_reaction_removal_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveVerifyResult sse_decode_archive_verify_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_box_autoadd_discovered_peer(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkPreviewRef sse_decode_box_autoadd_link_preview_ref(
    SseDeserializer deserializer,
  );

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_box_autoadd_user_profile(SseDeserializer deserializer);

  @protected
  VideoThumbRef sse_decode_box_autoadd_video_thumb_ref(
    SseDeserializer deserializer,
  );

  @protected
  ChannelFfi sse_decode_channel_ffi(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_discovered_peer(SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FriendFfi sse_decode_friend_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer);

  @protected
  LabelFfi sse_decode_label_ffi(SseDeserializer deserializer);

  @protected
  LinkPreviewRef sse_decode_link_preview_ref(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ArchiveChannelInfoFfi> sse_decode_list_archive_channel_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveDeletionFfi> sse_decode_list_archive_deletion_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveEditFfi> sse_decode_list_archive_edit_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveFileFfi> sse_decode_list_archive_file_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveMessageFfi> sse_decode_list_archive_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchivePubKeyFfi> sse_decode_list_archive_pub_key_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveReactionFfi> sse_decode_list_archive_reaction_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveReactionRemovalFfi> sse_decode_list_archive_reaction_removal_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ChannelFfi> sse_decode_list_channel_ffi(SseDeserializer deserializer);

  @protected
  List<FriendFfi> sse_decode_list_friend_ffi(SseDeserializer deserializer);

  @protected
  List<LabelFfi> sse_decode_list_label_ffi(SseDeserializer deserializer);

  @protected
  List<MemberFfi> sse_decode_list_member_ffi(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, PlatformInt64)> sse_decode_list_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<ServerFfi> sse_decode_list_server_ffi(SseDeserializer deserializer);

  @protected
  List<ShareEntry> sse_decode_list_share_entry(SseDeserializer deserializer);

  @protected
  List<StoredChannelMessage> sse_decode_list_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredFileInfo> sse_decode_list_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessageEdit> sse_decode_list_stored_message_edit(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredReaction> sse_decode_list_stored_reaction(
    SseDeserializer deserializer,
  );

  @protected
  List<UserProfile> sse_decode_list_user_profile(SseDeserializer deserializer);

  @protected
  List<VaultFileStatusFfi> sse_decode_list_vault_file_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MemberFfi sse_decode_member_ffi(SseDeserializer deserializer);

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkPreviewRef? sse_decode_opt_box_autoadd_link_preview_ref(
    SseDeserializer deserializer,
  );

  @protected
  NetworkEvent? sse_decode_opt_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo? sse_decode_opt_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile? sse_decode_opt_box_autoadd_user_profile(
    SseDeserializer deserializer,
  );

  @protected
  VideoThumbRef? sse_decode_opt_box_autoadd_video_thumb_ref(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (String, PlatformInt64) sse_decode_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  ServerFfi sse_decode_server_ffi(SseDeserializer deserializer);

  @protected
  ShardImportResultFfi sse_decode_shard_import_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ShareEntry sse_decode_share_entry(SseDeserializer deserializer);

  @protected
  ShareLinkInfo sse_decode_share_link_info(SseDeserializer deserializer);

  @protected
  StorageStatsFfi sse_decode_storage_stats_ffi(SseDeserializer deserializer);

  @protected
  StoredChannelMessage sse_decode_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_stored_file_info(SseDeserializer deserializer);

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer);

  @protected
  StoredMessageEdit sse_decode_stored_message_edit(
    SseDeserializer deserializer,
  );

  @protected
  StoredReaction sse_decode_stored_reaction(SseDeserializer deserializer);

  @protected
  TwitchDeviceFlowResult sse_decode_twitch_device_flow_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultFileStatusFfi sse_decode_vault_file_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  VideoThumbRef sse_decode_video_thumb_ref(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_progress_Sse(
    RustStreamSink<DownloadProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_network_event_Sse(
    RustStreamSink<NetworkEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_channel_info_ffi(
    ArchiveChannelInfoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_data(ArchiveData self, SseSerializer serializer);

  @protected
  void sse_encode_archive_deletion_ffi(
    ArchiveDeletionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_edit_ffi(
    ArchiveEditFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_file_ffi(
    ArchiveFileFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_message_ffi(
    ArchiveMessageFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_pub_key_ffi(
    ArchivePubKeyFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_reaction_ffi(
    ArchiveReactionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_reaction_removal_ffi(
    ArchiveReactionRemovalFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_verify_result(
    ArchiveVerifyResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_link_preview_ref(
    LinkPreviewRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_event(
    NetworkEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_profile(
    UserProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_video_thumb_ref(
    VideoThumbRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_ffi(ChannelFfi self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_progress(
    DownloadProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_friend_ffi(FriendFfi self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_label_ffi(LabelFfi self, SseSerializer serializer);

  @protected
  void sse_encode_link_preview_ref(
    LinkPreviewRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_archive_channel_info_ffi(
    List<ArchiveChannelInfoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_deletion_ffi(
    List<ArchiveDeletionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_edit_ffi(
    List<ArchiveEditFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_file_ffi(
    List<ArchiveFileFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_message_ffi(
    List<ArchiveMessageFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_pub_key_ffi(
    List<ArchivePubKeyFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_reaction_ffi(
    List<ArchiveReactionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_reaction_removal_ffi(
    List<ArchiveReactionRemovalFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_channel_ffi(
    List<ChannelFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_ffi(
    List<FriendFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_label_ffi(List<LabelFfi> self, SseSerializer serializer);

  @protected
  void sse_encode_list_member_ffi(
    List<MemberFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_64(
    List<(String, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_ffi(
    List<ServerFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_share_entry(
    List<ShareEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_channel_message(
    List<StoredChannelMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_file_info(
    List<StoredFileInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message_edit(
    List<StoredMessageEdit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_reaction(
    List<StoredReaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_profile(
    List<UserProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_file_status_ffi(
    List<VaultFileStatusFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_member_ffi(MemberFfi self, SseSerializer serializer);

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_link_preview_ref(
    LinkPreviewRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_network_event(
    NetworkEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_file_info(
    StoredFileInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_profile(
    UserProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_video_thumb_ref(
    VideoThumbRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_i_64(
    (String, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_ffi(ServerFfi self, SseSerializer serializer);

  @protected
  void sse_encode_shard_import_result_ffi(
    ShardImportResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_entry(ShareEntry self, SseSerializer serializer);

  @protected
  void sse_encode_share_link_info(ShareLinkInfo self, SseSerializer serializer);

  @protected
  void sse_encode_storage_stats_ffi(
    StorageStatsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_channel_message(
    StoredChannelMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer);

  @protected
  void sse_encode_stored_message_edit(
    StoredMessageEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_reaction(
    StoredReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_twitch_device_flow_result(
    TwitchDeviceFlowResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_file_status_ffi(
    VaultFileStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_thumb_ref(VideoThumbRef self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
