// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crdt.dart';
import 'api/identity.dart';
import 'api/network.dart';
import 'api/simple.dart';
import 'api/storage.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<NetworkEvent> dco_decode_StreamSink_network_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_box_autoadd_discovered_peer(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw);

  @protected
  StoredFileInfo dco_decode_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile dco_decode_box_autoadd_user_profile(dynamic raw);

  @protected
  ChannelFfi dco_decode_channel_ffi(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_discovered_peer(dynamic raw);

  @protected
  FriendFfi dco_decode_friend_ffi(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChannelFfi> dco_decode_list_channel_ffi(dynamic raw);

  @protected
  List<FriendFfi> dco_decode_list_friend_ffi(dynamic raw);

  @protected
  List<MemberFfi> dco_decode_list_member_ffi(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ServerFfi> dco_decode_list_server_ffi(dynamic raw);

  @protected
  List<StoredChannelMessage> dco_decode_list_stored_channel_message(
    dynamic raw,
  );

  @protected
  List<StoredFileInfo> dco_decode_list_stored_file_info(dynamic raw);

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw);

  @protected
  List<StoredReaction> dco_decode_list_stored_reaction(dynamic raw);

  @protected
  List<UserProfile> dco_decode_list_user_profile(dynamic raw);

  @protected
  MemberFfi dco_decode_member_ffi(dynamic raw);

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NetworkEvent? dco_decode_opt_box_autoadd_network_event(dynamic raw);

  @protected
  StoredFileInfo? dco_decode_opt_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile? dco_decode_opt_box_autoadd_user_profile(dynamic raw);

  @protected
  ServerFfi dco_decode_server_ffi(dynamic raw);

  @protected
  StoredChannelMessage dco_decode_stored_channel_message(dynamic raw);

  @protected
  StoredFileInfo dco_decode_stored_file_info(dynamic raw);

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw);

  @protected
  StoredReaction dco_decode_stored_reaction(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<NetworkEvent> sse_decode_StreamSink_network_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_box_autoadd_discovered_peer(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_box_autoadd_user_profile(SseDeserializer deserializer);

  @protected
  ChannelFfi sse_decode_channel_ffi(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_discovered_peer(SseDeserializer deserializer);

  @protected
  FriendFfi sse_decode_friend_ffi(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChannelFfi> sse_decode_list_channel_ffi(SseDeserializer deserializer);

  @protected
  List<FriendFfi> sse_decode_list_friend_ffi(SseDeserializer deserializer);

  @protected
  List<MemberFfi> sse_decode_list_member_ffi(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ServerFfi> sse_decode_list_server_ffi(SseDeserializer deserializer);

  @protected
  List<StoredChannelMessage> sse_decode_list_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredFileInfo> sse_decode_list_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredReaction> sse_decode_list_stored_reaction(
    SseDeserializer deserializer,
  );

  @protected
  List<UserProfile> sse_decode_list_user_profile(SseDeserializer deserializer);

  @protected
  MemberFfi sse_decode_member_ffi(SseDeserializer deserializer);

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NetworkEvent? sse_decode_opt_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo? sse_decode_opt_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile? sse_decode_opt_box_autoadd_user_profile(
    SseDeserializer deserializer,
  );

  @protected
  ServerFfi sse_decode_server_ffi(SseDeserializer deserializer);

  @protected
  StoredChannelMessage sse_decode_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_stored_file_info(SseDeserializer deserializer);

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer);

  @protected
  StoredReaction sse_decode_stored_reaction(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_network_event_Sse(
    RustStreamSink<NetworkEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_event(
    NetworkEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_profile(
    UserProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_ffi(ChannelFfi self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_friend_ffi(FriendFfi self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_ffi(
    List<ChannelFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_friend_ffi(
    List<FriendFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_ffi(
    List<MemberFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_ffi(
    List<ServerFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_channel_message(
    List<StoredChannelMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_file_info(
    List<StoredFileInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_reaction(
    List<StoredReaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_profile(
    List<UserProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_member_ffi(MemberFfi self, SseSerializer serializer);

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_network_event(
    NetworkEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_file_info(
    StoredFileInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_profile(
    UserProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_ffi(ServerFfi self, SseSerializer serializer);

  @protected
  void sse_encode_stored_channel_message(
    StoredChannelMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer);

  @protected
  void sse_encode_stored_reaction(
    StoredReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
