// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Export a DM conversation as a `.hollow-archive` file.
/// `file_mode`: "full", "images_only", or "placeholder".
/// Returns the file size in bytes on success.
Future<BigInt> exportDmArchive({
  required String peerId,
  required String outputPath,
  required String fileMode,
}) => RustLib.instance.api.crateApiArchiveExportDmArchive(
  peerId: peerId,
  outputPath: outputPath,
  fileMode: fileMode,
);

/// Export a channel conversation as a `.hollow-archive` file.
/// `file_mode`: "full", "images_only", or "placeholder".
/// Returns the file size in bytes on success.
Future<BigInt> exportChannelArchive({
  required String serverId,
  required String channelId,
  String? channelName,
  required String outputPath,
  required String fileMode,
}) => RustLib.instance.api.crateApiArchiveExportChannelArchive(
  serverId: serverId,
  channelId: channelId,
  channelName: channelName,
  outputPath: outputPath,
  fileMode: fileMode,
);

/// Export all text channels of a server as a single `.hollow-archive` file.
/// `channels_json`: JSON array of `[{"channel_id": "...", "channel_name": "..."}]`.
/// `file_mode`: "full", "images_only", or "placeholder".
/// Returns the file size in bytes on success.
Future<BigInt> exportServerArchive({
  required String serverId,
  required String serverName,
  required String channelsJson,
  required String outputPath,
  required String fileMode,
}) => RustLib.instance.api.crateApiArchiveExportServerArchive(
  serverId: serverId,
  serverName: serverName,
  channelsJson: channelsJson,
  outputPath: outputPath,
  fileMode: fileMode,
);

/// Verify a `.hollow-archive` file. Quick check — parses manifest + signatures,
/// reports validity summary without loading full message data.
Future<ArchiveVerifyResult> verifyArchive({required String archivePath}) =>
    RustLib.instance.api.crateApiArchiveVerifyArchive(archivePath: archivePath);

/// Load a `.hollow-archive` file for rendering in the POV viewer.
/// Full parse: returns all messages, edits, deletions, files, and verification results.
Future<ArchiveData> loadArchive({required String archivePath}) =>
    RustLib.instance.api.crateApiArchiveLoadArchive(archivePath: archivePath);

/// Export all vault shards for a server as a `.hollow-shards` ZIP bundle.
/// Contains manifest.json + shards/{content_id}/{shard_index}.shard files.
/// Returns the file size in bytes on success.
Future<BigInt> exportServerShards({
  required String serverId,
  required String outputPath,
}) => RustLib.instance.api.crateApiArchiveExportServerShards(
  serverId: serverId,
  outputPath: outputPath,
);

/// Import a `.hollow-shards` ZIP bundle. Stores new manifests and shards
/// that are not already present locally. Returns a summary of what was imported.
Future<ShardImportResultFfi> importServerShards({
  required String archivePath,
}) => RustLib.instance.api.crateApiArchiveImportServerShards(
  archivePath: archivePath,
);

/// Channel info for multi-channel (server) archives.
class ArchiveChannelInfoFfi {
  final String channelId;
  final String channelName;
  final int messageCount;

  const ArchiveChannelInfoFfi({
    required this.channelId,
    required this.channelName,
    required this.messageCount,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^ channelName.hashCode ^ messageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveChannelInfoFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          channelName == other.channelName &&
          messageCount == other.messageCount;
}

/// Full loaded archive data for the POV viewer.
class ArchiveData {
  final String archiveType;
  final String exporterPeerId;
  final PlatformInt64 exportTimestamp;
  final String fileMode;
  final String? peerId;
  final String? serverId;
  final String? channelId;
  final String? channelName;
  final String? serverName;
  final List<ArchiveChannelInfoFfi> channels;
  final List<String> participants;
  final List<ArchiveMessageFfi> messages;
  final List<ArchiveEditFfi> edits;
  final List<ArchiveDeletionFfi> deletions;
  final List<ArchiveReactionRemovalFfi> reactionRemovals;
  final List<ArchivePubKeyFfi> pubkeys;
  final List<ArchiveFileFfi> files;
  final ArchiveVerifyResult verification;

  /// Path to temp directory with extracted file bytes (if any).
  final String? filesDir;

  const ArchiveData({
    required this.archiveType,
    required this.exporterPeerId,
    required this.exportTimestamp,
    required this.fileMode,
    this.peerId,
    this.serverId,
    this.channelId,
    this.channelName,
    this.serverName,
    required this.channels,
    required this.participants,
    required this.messages,
    required this.edits,
    required this.deletions,
    required this.reactionRemovals,
    required this.pubkeys,
    required this.files,
    required this.verification,
    this.filesDir,
  });

  @override
  int get hashCode =>
      archiveType.hashCode ^
      exporterPeerId.hashCode ^
      exportTimestamp.hashCode ^
      fileMode.hashCode ^
      peerId.hashCode ^
      serverId.hashCode ^
      channelId.hashCode ^
      channelName.hashCode ^
      serverName.hashCode ^
      channels.hashCode ^
      participants.hashCode ^
      messages.hashCode ^
      edits.hashCode ^
      deletions.hashCode ^
      reactionRemovals.hashCode ^
      pubkeys.hashCode ^
      files.hashCode ^
      verification.hashCode ^
      filesDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveData &&
          runtimeType == other.runtimeType &&
          archiveType == other.archiveType &&
          exporterPeerId == other.exporterPeerId &&
          exportTimestamp == other.exportTimestamp &&
          fileMode == other.fileMode &&
          peerId == other.peerId &&
          serverId == other.serverId &&
          channelId == other.channelId &&
          channelName == other.channelName &&
          serverName == other.serverName &&
          channels == other.channels &&
          participants == other.participants &&
          messages == other.messages &&
          edits == other.edits &&
          deletions == other.deletions &&
          reactionRemovals == other.reactionRemovals &&
          pubkeys == other.pubkeys &&
          files == other.files &&
          verification == other.verification &&
          filesDir == other.filesDir;
}

/// A deletion evidence entry.
class ArchiveDeletionFfi {
  final String messageId;
  final String deletedText;
  final PlatformInt64 deletedAt;
  final String? signature;
  final String? publicKey;

  const ArchiveDeletionFfi({
    required this.messageId,
    required this.deletedText,
    required this.deletedAt,
    this.signature,
    this.publicKey,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      deletedText.hashCode ^
      deletedAt.hashCode ^
      signature.hashCode ^
      publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveDeletionFfi &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          deletedText == other.deletedText &&
          deletedAt == other.deletedAt &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

/// An edit history entry.
class ArchiveEditFfi {
  final String messageId;
  final String oldText;
  final String newText;
  final PlatformInt64 editedAt;
  final String? signature;
  final String? publicKey;
  final String? prevSignature;
  final String? prevPublicKey;
  final PlatformInt64? prevTimestamp;

  const ArchiveEditFfi({
    required this.messageId,
    required this.oldText,
    required this.newText,
    required this.editedAt,
    this.signature,
    this.publicKey,
    this.prevSignature,
    this.prevPublicKey,
    this.prevTimestamp,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      oldText.hashCode ^
      newText.hashCode ^
      editedAt.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      prevSignature.hashCode ^
      prevPublicKey.hashCode ^
      prevTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveEditFfi &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          oldText == other.oldText &&
          newText == other.newText &&
          editedAt == other.editedAt &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          prevSignature == other.prevSignature &&
          prevPublicKey == other.prevPublicKey &&
          prevTimestamp == other.prevTimestamp;
}

/// File metadata from an archive.
class ArchiveFileFfi {
  final String fileId;
  final String fileName;
  final String fileExt;
  final String mimeType;
  final BigInt sizeBytes;
  final bool isImage;
  final int? width;
  final int? height;
  final String? sha256;
  final bool included;

  const ArchiveFileFfi({
    required this.fileId,
    required this.fileName,
    required this.fileExt,
    required this.mimeType,
    required this.sizeBytes,
    required this.isImage,
    this.width,
    this.height,
    this.sha256,
    required this.included,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      fileName.hashCode ^
      fileExt.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      isImage.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sha256.hashCode ^
      included.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveFileFfi &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          fileName == other.fileName &&
          fileExt == other.fileExt &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          isImage == other.isImage &&
          width == other.width &&
          height == other.height &&
          sha256 == other.sha256 &&
          included == other.included;
}

/// A single message from an imported archive.
class ArchiveMessageFfi {
  final String messageId;
  final String senderId;
  final String text;
  final PlatformInt64 timestamp;
  final String? signature;
  final String? publicKey;
  final PlatformInt64? editedAt;
  final PlatformInt64? hiddenAt;
  final String? replyToMid;
  final String? fileId;

  /// Channel ID — populated only in server (multi-channel) archives.
  final String? channelId;
  final List<ArchiveReactionFfi> reactions;

  /// Whether this message's signature is valid (None if not yet verified).
  final bool? signatureValid;

  const ArchiveMessageFfi({
    required this.messageId,
    required this.senderId,
    required this.text,
    required this.timestamp,
    this.signature,
    this.publicKey,
    this.editedAt,
    this.hiddenAt,
    this.replyToMid,
    this.fileId,
    this.channelId,
    required this.reactions,
    this.signatureValid,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      senderId.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      editedAt.hashCode ^
      hiddenAt.hashCode ^
      replyToMid.hashCode ^
      fileId.hashCode ^
      channelId.hashCode ^
      reactions.hashCode ^
      signatureValid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveMessageFfi &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          senderId == other.senderId &&
          text == other.text &&
          timestamp == other.timestamp &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          editedAt == other.editedAt &&
          hiddenAt == other.hiddenAt &&
          replyToMid == other.replyToMid &&
          fileId == other.fileId &&
          channelId == other.channelId &&
          reactions == other.reactions &&
          signatureValid == other.signatureValid;
}

/// A public key entry for offline verification.
class ArchivePubKeyFfi {
  final String peerId;
  final String publicKeyB64;

  const ArchivePubKeyFfi({required this.peerId, required this.publicKeyB64});

  @override
  int get hashCode => peerId.hashCode ^ publicKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchivePubKeyFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          publicKeyB64 == other.publicKeyB64;
}

/// A reaction on a message.
class ArchiveReactionFfi {
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;
  final String? signature;
  final String? publicKey;

  const ArchiveReactionFfi({
    required this.emoji,
    required this.peerId,
    required this.addedAt,
    this.signature,
    this.publicKey,
  });

  @override
  int get hashCode =>
      emoji.hashCode ^
      peerId.hashCode ^
      addedAt.hashCode ^
      signature.hashCode ^
      publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveReactionFfi &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

/// A reaction removal evidence entry.
class ArchiveReactionRemovalFfi {
  final String messageId;
  final String emoji;
  final String peerId;
  final PlatformInt64 removedAt;
  final String? signature;
  final String? publicKey;

  const ArchiveReactionRemovalFfi({
    required this.messageId,
    required this.emoji,
    required this.peerId,
    required this.removedAt,
    this.signature,
    this.publicKey,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      emoji.hashCode ^
      peerId.hashCode ^
      removedAt.hashCode ^
      signature.hashCode ^
      publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveReactionRemovalFfi &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          removedAt == other.removedAt &&
          signature == other.signature &&
          publicKey == other.publicKey;
}

/// Summary result from verifying an archive.
class ArchiveVerifyResult {
  final String archiveType;
  final String exporterPeerId;
  final PlatformInt64 exportTimestamp;
  final int messageCount;
  final bool archiveSignatureValid;
  final int messagesWithValidSig;
  final int messagesWithInvalidSig;
  final int messagesWithoutSig;
  final List<String> participantIds;
  final String? peerId;
  final String? serverId;
  final String? channelId;
  final String? channelName;
  final String? serverName;
  final List<ArchiveChannelInfoFfi> channels;

  const ArchiveVerifyResult({
    required this.archiveType,
    required this.exporterPeerId,
    required this.exportTimestamp,
    required this.messageCount,
    required this.archiveSignatureValid,
    required this.messagesWithValidSig,
    required this.messagesWithInvalidSig,
    required this.messagesWithoutSig,
    required this.participantIds,
    this.peerId,
    this.serverId,
    this.channelId,
    this.channelName,
    this.serverName,
    required this.channels,
  });

  @override
  int get hashCode =>
      archiveType.hashCode ^
      exporterPeerId.hashCode ^
      exportTimestamp.hashCode ^
      messageCount.hashCode ^
      archiveSignatureValid.hashCode ^
      messagesWithValidSig.hashCode ^
      messagesWithInvalidSig.hashCode ^
      messagesWithoutSig.hashCode ^
      participantIds.hashCode ^
      peerId.hashCode ^
      serverId.hashCode ^
      channelId.hashCode ^
      channelName.hashCode ^
      serverName.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveVerifyResult &&
          runtimeType == other.runtimeType &&
          archiveType == other.archiveType &&
          exporterPeerId == other.exporterPeerId &&
          exportTimestamp == other.exportTimestamp &&
          messageCount == other.messageCount &&
          archiveSignatureValid == other.archiveSignatureValid &&
          messagesWithValidSig == other.messagesWithValidSig &&
          messagesWithInvalidSig == other.messagesWithInvalidSig &&
          messagesWithoutSig == other.messagesWithoutSig &&
          participantIds == other.participantIds &&
          peerId == other.peerId &&
          serverId == other.serverId &&
          channelId == other.channelId &&
          channelName == other.channelName &&
          serverName == other.serverName &&
          channels == other.channels;
}

/// Result of importing a `.hollow-shards` bundle.
class ShardImportResultFfi {
  final String serverId;
  final int manifestsImported;
  final int shardsImported;
  final int shardsSkipped;
  final int newReconstructable;

  const ShardImportResultFfi({
    required this.serverId,
    required this.manifestsImported,
    required this.shardsImported,
    required this.shardsSkipped,
    required this.newReconstructable,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      manifestsImported.hashCode ^
      shardsImported.hashCode ^
      shardsSkipped.hashCode ^
      newReconstructable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShardImportResultFfi &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          manifestsImported == other.manifestsImported &&
          shardsImported == other.shardsImported &&
          shardsSkipped == other.shardsSkipped &&
          newReconstructable == other.newReconstructable;
}
