// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new server. Returns the server_id.
Future<String> createServer({required String name}) =>
    RustLib.instance.api.crateApiCrdtCreateServer(name: name);

/// Create a channel in a server. Returns "pending" (actual channel_id comes via event).
Future<String> createChannel({
  required String serverId,
  required String name,
  String? category,
}) => RustLib.instance.api.crateApiCrdtCreateChannel(
  serverId: serverId,
  name: name,
  category: category,
);

/// Remove a channel from a server.
Future<void> removeChannel({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiCrdtRemoveChannel(
  serverId: serverId,
  channelId: channelId,
);

/// Get all servers the user has joined. Reads from the local DB.
Future<List<ServerFfi>> getJoinedServers() =>
    RustLib.instance.api.crateApiCrdtGetJoinedServers();

/// Get channels for a specific server. Reads from the local DB.
Future<List<ChannelFfi>> getServerChannels({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerChannels(serverId: serverId);

/// Get members for a specific server. Reads from the local DB.
Future<List<MemberFfi>> getServerMembers({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerMembers(serverId: serverId);

/// Get a server setting value by key. Returns empty string if not set.
Future<String> getServerSetting({
  required String serverId,
  required String key,
}) => RustLib.instance.api.crateApiCrdtGetServerSetting(
  serverId: serverId,
  key: key,
);

/// Rename a server.
Future<void> renameServer({
  required String serverId,
  required String newName,
}) => RustLib.instance.api.crateApiCrdtRenameServer(
  serverId: serverId,
  newName: newName,
);

/// Rename a channel in a server.
Future<void> renameChannel({
  required String serverId,
  required String channelId,
  required String newName,
}) => RustLib.instance.api.crateApiCrdtRenameChannel(
  serverId: serverId,
  channelId: channelId,
  newName: newName,
);

/// Update a server setting (key-value pair).
Future<void> updateServerSetting({
  required String serverId,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiCrdtUpdateServerSetting(
  serverId: serverId,
  key: key,
  value: value,
);

/// Join a server via invite link. Connects to the server's signaling room and
/// requests membership from existing members.
Future<void> joinServer({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtJoinServer(serverId: serverId);

/// Get the local user's role in a server.
/// Returns "owner", "admin", "moderator", or "member".
Future<String> getMyRole({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetMyRole(serverId: serverId);

/// Get the local user's permissions bitmask in a server.
Future<int> getMyPermissions({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetMyPermissions(serverId: serverId);

/// Change a member's role in a server.
/// Requires MANAGE_ROLES permission and must outrank the target.
Future<void> changeMemberRole({
  required String serverId,
  required String peerId,
  required String newRole,
}) => RustLib.instance.api.crateApiCrdtChangeMemberRole(
  serverId: serverId,
  peerId: peerId,
  newRole: newRole,
);

/// Kick a member from a server.
/// Requires KICK_MEMBERS permission and must outrank the target.
Future<void> kickMember({required String serverId, required String peerId}) =>
    RustLib.instance.api.crateApiCrdtKickMember(
      serverId: serverId,
      peerId: peerId,
    );

/// Set a member's server nickname. Pass an empty string to clear.
Future<void> setNickname({
  required String serverId,
  required String peerId,
  required String nickname,
}) => RustLib.instance.api.crateApiCrdtSetNickname(
  serverId: serverId,
  peerId: peerId,
  nickname: nickname,
);

/// Pin a message in a channel. Requires MANAGE_CHANNELS permission.
Future<void> pinMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiCrdtPinMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Unpin a message from a channel. Requires MANAGE_CHANNELS permission.
Future<void> unpinMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiCrdtUnpinMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Get pinned message IDs for a channel.
Future<List<String>> getPinnedMessages({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiCrdtGetPinnedMessages(
  serverId: serverId,
  channelId: channelId,
);

/// Delete a server entirely (removes from local DB and memory).
Future<void> deleteServer({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtDeleteServer(serverId: serverId);

/// Channel info for FFI (Dart-visible).
class ChannelFfi {
  final String channelId;
  final String name;
  final String? category;

  const ChannelFfi({
    required this.channelId,
    required this.name,
    this.category,
  });

  @override
  int get hashCode => channelId.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category;
}

/// Member info for FFI (Dart-visible).
class MemberFfi {
  final String peerId;
  final String displayName;
  final String role;
  final String nickname;

  const MemberFfi({
    required this.peerId,
    required this.displayName,
    required this.role,
    required this.nickname,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      role.hashCode ^
      nickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          role == other.role &&
          nickname == other.nickname;
}

/// Server info for FFI (Dart-visible).
class ServerFfi {
  final String serverId;
  final String name;
  final int memberCount;
  final int channelCount;

  const ServerFfi({
    required this.serverId,
    required this.name,
    required this.memberCount,
    required this.channelCount,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      name.hashCode ^
      memberCount.hashCode ^
      channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerFfi &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          name == other.name &&
          memberCount == other.memberCount &&
          channelCount == other.channelCount;
}
