// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Load the saved identity from disk, or create a new one if none exists.
/// On first run, returns the mnemonic phrase for the user to back up.
/// On subsequent runs, returns just the peer ID (mnemonic is not stored).
Future<IdentityInfo> loadOrCreateIdentity() =>
    RustLib.instance.api.crateApiIdentityLoadOrCreateIdentity();

/// Generate a fresh identity, replacing any existing one.
/// Returns the new peer ID and mnemonic phrase.
Future<IdentityInfo> generateNewIdentity() =>
    RustLib.instance.api.crateApiIdentityGenerateNewIdentity();

/// Restore an identity from a 24-word mnemonic phrase.
/// Replaces any existing identity on disk.
Future<IdentityInfo> restoreIdentityFromMnemonic({required String phrase}) =>
    RustLib.instance.api.crateApiIdentityRestoreIdentityFromMnemonic(
      phrase: phrase,
    );

/// Result of creating or loading an identity.
class IdentityInfo {
  final String peerId;

  /// The 24-word mnemonic phrase. Only present on first creation — save it!
  final String? mnemonic;

  const IdentityInfo({required this.peerId, this.mnemonic});

  @override
  int get hashCode => peerId.hashCode ^ mnemonic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          mnemonic == other.mnemonic;
}
