// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Set the data directory path (Android/iOS: pass app documents dir).
/// Must be called before load_or_create_identity() or start_node().
Future<void> setDataDir({required String path}) =>
    RustLib.instance.api.crateApiIdentitySetDataDir(path: path);

/// Load the saved identity from disk, or create a new one if none exists.
/// On first run, returns the mnemonic phrase for the user to back up.
/// On subsequent runs, returns just the peer ID (mnemonic is not stored).
Future<IdentityInfo> loadOrCreateIdentity() =>
    RustLib.instance.api.crateApiIdentityLoadOrCreateIdentity();

/// Generate a fresh identity, replacing any existing one.
/// Returns the new peer ID and mnemonic phrase.
Future<IdentityInfo> generateNewIdentity() =>
    RustLib.instance.api.crateApiIdentityGenerateNewIdentity();

/// Restore an identity from a 24-word mnemonic phrase.
/// Replaces any existing identity on disk.
Future<IdentityInfo> restoreIdentityFromMnemonic({required String phrase}) =>
    RustLib.instance.api.crateApiIdentityRestoreIdentityFromMnemonic(
      phrase: phrase,
    );

/// Unlock the identity file for this session.
/// For plaintext identities: loads directly (password ignored).
/// For encrypted identities: decrypts using password and/or OS keychain.
/// Must be called before open_message_store() or start_node().
Future<IdentityInfo> unlockIdentity({String? password}) =>
    RustLib.instance.api.crateApiIdentityUnlockIdentity(password: password);

/// Clear the session wrapping key. After this, all identity operations
/// will fail until unlock_identity() is called again.
Future<void> lockIdentity() =>
    RustLib.instance.api.crateApiIdentityLockIdentity();

/// Enable password protection on the current identity.
/// If `require_on_launch` is true (flags=0x01), the password is required every launch.
/// If false (flags=0x03), the password-derived key is also stored in OS keychain
/// for silent unlock — identity is encrypted but app opens normally on this device.
Future<void> enablePasswordProtection({
  required String password,
  required bool requireOnLaunch,
}) => RustLib.instance.api.crateApiIdentityEnablePasswordProtection(
  password: password,
  requireOnLaunch: requireOnLaunch,
);

/// Change the app password. Requires the current password for verification.
/// Preserves the current require_on_launch setting (keychain flag).
Future<void> changePassword({
  required String oldPassword,
  required String newPassword,
}) => RustLib.instance.api.crateApiIdentityChangePassword(
  oldPassword: oldPassword,
  newPassword: newPassword,
);

/// Remove password protection. If OS keychain is available, transitions to
/// keychain-only protection. Otherwise writes plaintext.
Future<void> removePasswordProtection({required String password}) => RustLib
    .instance
    .api
    .crateApiIdentityRemovePasswordProtection(password: password);

/// Toggle whether the password is required on each app launch.
/// When true (flags=0x01): password prompt on every launch.
/// When false (flags=0x03): password-derived key cached in OS keychain, silent unlock.
/// Requires the identity to already be password-protected and unlocked.
Future<void> setRequirePasswordOnLaunch({required bool require}) => RustLib
    .instance
    .api
    .crateApiIdentitySetRequirePasswordOnLaunch(require: require);

/// Enable OS keychain (DPAPI/Keychain) protection on the current identity.
/// This is opt-in — the user must explicitly choose this from Settings.
/// Requires the identity to be currently unlocked and unencrypted (or keychain-already).
Future<void> enableOsKeychainProtection() =>
    RustLib.instance.api.crateApiIdentityEnableOsKeychainProtection();

/// Disable OS keychain protection — writes identity back as plaintext.
/// Requires the identity to be currently unlocked.
Future<void> disableOsKeychainProtection() =>
    RustLib.instance.api.crateApiIdentityDisableOsKeychainProtection();

/// Get the current protection status of the identity file.
Future<ProtectionStatus> getIdentityProtectionStatus() =>
    RustLib.instance.api.crateApiIdentityGetIdentityProtectionStatus();

/// Check if the identity is currently unlocked (session wrapping key is set).
Future<bool> isIdentityUnlocked() =>
    RustLib.instance.api.crateApiIdentityIsIdentityUnlocked();

/// Result of creating or loading an identity.
class IdentityInfo {
  final String peerId;

  /// The 24-word mnemonic phrase. Only present on first creation — save it!
  final String? mnemonic;

  const IdentityInfo({required this.peerId, this.mnemonic});

  @override
  int get hashCode => peerId.hashCode ^ mnemonic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          mnemonic == other.mnemonic;
}

/// Current protection status of the identity file.
class ProtectionStatus {
  final bool isEncrypted;
  final bool hasPassword;
  final bool hasOsKeychain;
  final bool osKeychainAvailable;

  const ProtectionStatus({
    required this.isEncrypted,
    required this.hasPassword,
    required this.hasOsKeychain,
    required this.osKeychainAvailable,
  });

  @override
  int get hashCode =>
      isEncrypted.hashCode ^
      hasPassword.hashCode ^
      hasOsKeychain.hashCode ^
      osKeychainAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtectionStatus &&
          runtimeType == other.runtimeType &&
          isEncrypted == other.isEncrypted &&
          hasPassword == other.hasPassword &&
          hasOsKeychain == other.hasOsKeychain &&
          osKeychainAvailable == other.osKeychainAvailable;
}
