// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_forwarding_task`, `get_event_rx`, `get_node`, `get_runtime`, `to_ffi_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeState`

/// Start the libp2p node with mDNS peer discovery and E2EE.
/// Uses the persistent identity from disk.
/// Returns the local peer ID as a string.
Future<String> startNode() => RustLib.instance.api.crateApiNetworkStartNode();

/// Stream network events to Dart in real time.
/// Must be called after `start_node()`. Can only be called once per node lifetime.
Stream<NetworkEvent> watchNetworkEvents() =>
    RustLib.instance.api.crateApiNetworkWatchNetworkEvents();

/// Poll for the next network event. Returns None if no event is available.
/// Fallback for when streaming is not active.
Future<NetworkEvent?> pollNetworkEvent() =>
    RustLib.instance.api.crateApiNetworkPollNetworkEvent();

/// Get the local peer ID. Returns None if the node hasn't started.
Future<String?> getLocalPeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalPeerId();

/// Get the Olm identity fingerprint (Curve25519 base64).
/// Returns None if the node hasn't started.
Future<String?> getOlmFingerprint() =>
    RustLib.instance.api.crateApiNetworkGetOlmFingerprint();

/// Send a text message to a peer. The peer must be reachable (discovered via mDNS).
Future<void> sendMessage({required String peerId, required String text}) =>
    RustLib.instance.api.crateApiNetworkSendMessage(peerId: peerId, text: text);

/// Join a room via the signaling service.
/// Registers our addresses and bootstraps from other peers in the room.
Future<void> joinRoom({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkJoinRoom(roomCode: roomCode);

/// Stop the running node.
Future<void> stopNode() => RustLib.instance.api.crateApiNetworkStopNode();

/// A discovered peer on the local network.
class DiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const DiscoveredPeer({required this.peerId, required this.addresses});

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.peerDiscovered({required DiscoveredPeer peer}) =
      NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.peerExpired({required String peerId}) =
      NetworkEvent_PeerExpired;
  const factory NetworkEvent.peerDisconnected({required String peerId}) =
      NetworkEvent_PeerDisconnected;
  const factory NetworkEvent.roomCleared() = NetworkEvent_RoomCleared;
  const factory NetworkEvent.listening({required String address}) =
      NetworkEvent_Listening;
  const factory NetworkEvent.messageReceived({
    required String fromPeer,
    required String text,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.messageSent({required String toPeer}) =
      NetworkEvent_MessageSent;
  const factory NetworkEvent.messageSendFailed({
    required String toPeer,
    required String error,
  }) = NetworkEvent_MessageSendFailed;
  const factory NetworkEvent.sessionEstablished({required String peerId}) =
      NetworkEvent_SessionEstablished;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
}
