// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_forwarding_task`, `get_event_rx`, `get_license_key`, `get_node`, `get_relay_domain`, `get_runtime`, `to_ffi_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

Future<void> setLicenseKey({String? key}) =>
    RustLib.instance.api.crateApiNetworkSetLicenseKey(key: key);

Future<void> setRelayUrl({String? domain}) =>
    RustLib.instance.api.crateApiNetworkSetRelayUrl(domain: domain);

/// Start the libp2p node with mDNS peer discovery and E2EE.
/// Uses the persistent identity from disk.
/// Returns the local peer ID as a string.
Future<String> startNode() => RustLib.instance.api.crateApiNetworkStartNode();

/// Stream network events to Dart in real time.
/// Must be called after `start_node()`. Can only be called once per node lifetime.
Stream<NetworkEvent> watchNetworkEvents() =>
    RustLib.instance.api.crateApiNetworkWatchNetworkEvents();

/// Poll for the next network event. Returns None if no event is available.
/// Fallback for when streaming is not active.
Future<NetworkEvent?> pollNetworkEvent() =>
    RustLib.instance.api.crateApiNetworkPollNetworkEvent();

/// Get the local peer ID. Returns None if the node hasn't started.
Future<String?> getLocalPeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalPeerId();

/// Get the Olm identity fingerprint (Curve25519 base64).
/// Returns None if the node hasn't started.
Future<String?> getOlmFingerprint() =>
    RustLib.instance.api.crateApiNetworkGetOlmFingerprint();

/// Get the local Ed25519 public key as base64-encoded protobuf.
/// Used by the Verify Peer screen to display "Your Fingerprint".
Future<String> getLocalPublicKey() =>
    RustLib.instance.api.crateApiNetworkGetLocalPublicKey();

/// Verify an Ed25519 message signature against a canonical payload.
///
/// Used by the Message Proof dialog ("The RAT Files") to show real-time
/// VERIFIED / INVALID status. Pure crypto — no node state needed.
///
/// Arguments:
/// - `sender_peer_id`: the sender's PeerId (Base58btc)
/// - `signature_b64`: base64-encoded Ed25519 signature
/// - `public_key_b64`: base64-encoded protobuf public key
/// - `canonical_payload`: the signing payload string (e.g. "hollow-msg:dm:...")
Future<bool> verifyMessageProof({
  required String senderPeerId,
  required String signatureB64,
  required String publicKeyB64,
  required String canonicalPayload,
}) => RustLib.instance.api.crateApiNetworkVerifyMessageProof(
  senderPeerId: senderPeerId,
  signatureB64: signatureB64,
  publicKeyB64: publicKeyB64,
  canonicalPayload: canonicalPayload,
);

/// Fetch OpenGraph metadata for a URL and return a link preview the sender
/// can embed in their next outgoing message. Runs on the shared Tokio
/// runtime. Fails silently at every step — the caller should treat errors
/// as "no preview" and send the message as plain text.
///
/// **Privacy:** This MUST only be called on the sender side. Receivers
/// render the preview from embedded data and never fetch the URL. See
/// `node::link_preview` for the full contract.
///
/// Phase 6.75.
Future<LinkPreviewRef> fetchLinkPreview({required String url}) =>
    RustLib.instance.api.crateApiNetworkFetchLinkPreview(url: url);

/// Send a text message to a peer. The peer must be reachable (discovered via mDNS).
Future<void> sendMessage({
  required String peerId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendMessage(
  peerId: peerId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Send a text message to a server channel.
/// The message will be encrypted and sent to all connected server members.
Future<void> sendChannelMessage({
  required String serverId,
  required String channelId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendChannelMessage(
  serverId: serverId,
  channelId: channelId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Edit a channel message. Broadcasts the edit to all server members.
Future<void> editChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  newText: newText,
);

/// Edit a DM message. Sends the edit to the DM peer.
Future<void> editDmMessage({
  required String peerId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditDmMessage(
  peerId: peerId,
  messageId: messageId,
  newText: newText,
);

/// Delete (hide) a channel message. Broadcasts the deletion to all server members.
/// The message stays in the DB (Rat Files evidence) but is hidden from UI.
Future<void> deleteChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Delete (hide) a DM message. Sends the deletion to the DM peer.
Future<void> deleteDmMessage({
  required String peerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteDmMessage(
  peerId: peerId,
  messageId: messageId,
);

/// Add an emoji reaction to a channel message.
Future<void> addChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a channel message.
Future<void> removeChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Add an emoji reaction to a DM message.
Future<void> addDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a DM message.
Future<void> removeDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Send a friend request to a peer.
Future<void> sendFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkSendFriendRequest(peerId: peerId);

/// Accept a friend request from a peer.
Future<void> acceptFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkAcceptFriendRequest(peerId: peerId);

/// Reject a friend request from a peer.
Future<void> rejectFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRejectFriendRequest(peerId: peerId);

/// Remove a friend.
Future<void> removeFriend({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRemoveFriend(peerId: peerId);

/// Send a typing indicator to peers. Ephemeral, not stored.
/// For DMs: server_id = "", channel_id = peer ID.
/// For channels: server_id and channel_id as normal.
Future<void> sendTypingIndicator({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkSendTypingIndicator(
  serverId: serverId,
  channelId: channelId,
);

/// Toggle invisible mode. Broadcasts StatusUpdate to all connected peers.
Future<void> setInvisible({required bool invisible}) =>
    RustLib.instance.api.crateApiNetworkSetInvisible(invisible: invisible);

/// Subscribe to specific channels in a server for topic-based relay routing.
/// Only messages for subscribed channels are delivered in real-time.
/// Unsubscribed channel messages are synced on-demand when navigating to them.
Future<void> subscribeChannels({
  required String serverId,
  required List<String> channelIds,
}) => RustLib.instance.api.crateApiNetworkSubscribeChannels(
  serverId: serverId,
  channelIds: channelIds,
);

/// Request message sync for a specific channel from all connected server members.
/// Called when the user opens a channel to catch up on missed messages.
Future<void> requestChannelSync({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkRequestChannelSync(
  serverId: serverId,
  channelId: channelId,
);

/// Notify all connected peers that we're shutting down gracefully.
/// Call this before closing the app so peers can immediately update their state.
/// Update our display name, status, about me, and optionally avatar/banner —
/// saves to DB and broadcasts to all connected peers.
Future<void> updateProfile({
  required String displayName,
  required String status,
  required String aboutMe,
  Uint8List? avatarBytes,
  Uint8List? bannerBytes,
  required String twitchUsername,
}) => RustLib.instance.api.crateApiNetworkUpdateProfile(
  displayName: displayName,
  status: status,
  aboutMe: aboutMe,
  avatarBytes: avatarBytes,
  bannerBytes: bannerBytes,
  twitchUsername: twitchUsername,
);

/// Process a raw image into avatar format (128x128 WebP). Returns processed bytes.
Future<Uint8List> processAvatar({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessAvatar(rawBytes: rawBytes);

/// Process a raw image into banner format (600x200 WebP). Returns processed bytes.
Future<Uint8List> processBanner({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessBanner(rawBytes: rawBytes);

Future<void> notifyShutdown() =>
    RustLib.instance.api.crateApiNetworkNotifyShutdown();

/// Join a room via the signaling service.
/// Registers our addresses and bootstraps from other peers in the room.
Future<void> joinRoom({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkJoinRoom(roomCode: roomCode);

/// Stop the running node.
Future<void> stopNode() => RustLib.instance.api.crateApiNetworkStopNode();

/// Send a file to a DM peer or server channel.
/// `peer_id`: target peer (for DMs, empty for channels).
/// `server_id` + `channel_id`: target channel (for servers, empty for DMs).
/// `vthumb`: optional video thumbnail back-reference. When set, the file at
///           `file_path` is a thumbnail image for the vault-stored video
///           identified by `vthumb.cid`. Phase 6.75 video preview.
/// `override_width` / `override_height`: Phase 6.75 video preview — when the
///           file at `file_path` is a video, Dart passes the video's pixel
///           dimensions here so the FileHeader carries them and receivers can
///           render the bubble at the correct aspect ratio. Ignored for image
///           files (Rust extracts those dimensions itself).
Future<void> sendFile({
  String? peerId,
  String? serverId,
  String? channelId,
  required String filePath,
  required String messageId,
  required String messageText,
  VideoThumbRef? vthumb,
  int? overrideWidth,
  int? overrideHeight,
  String? shareRootHash,
  String? shareKeyHex,
}) => RustLib.instance.api.crateApiNetworkSendFile(
  peerId: peerId,
  serverId: serverId,
  channelId: channelId,
  filePath: filePath,
  messageId: messageId,
  messageText: messageText,
  vthumb: vthumb,
  overrideWidth: overrideWidth,
  overrideHeight: overrideHeight,
  shareRootHash: shareRootHash,
  shareKeyHex: shareKeyHex,
);

/// Request file chunks from a specific peer.
Future<void> requestFileFromPeer({
  required String fileId,
  required String peerId,
  required List<int> chunks,
}) => RustLib.instance.api.crateApiNetworkRequestFileFromPeer(
  fileId: fileId,
  peerId: peerId,
  chunks: chunks,
);

/// Convert a WebP image file to another format (PNG/JPEG).
/// Used for "Save As" functionality.
Future<Uint8List> convertImageFormat({
  required String sourcePath,
  required String targetFormat,
}) => RustLib.instance.api.crateApiNetworkConvertImageFormat(
  sourcePath: sourcePath,
  targetFormat: targetFormat,
);

/// Get the files directory path.
Future<String> getFilesDir() =>
    RustLib.instance.api.crateApiNetworkGetFilesDir();

/// Log a message from Dart to hollow_debug.log (visible in release builds).
Future<void> logFromDart({required String message}) =>
    RustLib.instance.api.crateApiNetworkLogFromDart(message: message);

/// Notify Rust that a WebRTC data channel is established with a peer.
Future<void> webrtcPeerConnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerConnected(peerId: peerId);

/// Notify Rust that a WebRTC data channel has been closed for a peer.
Future<void> webrtcPeerDisconnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerDisconnected(peerId: peerId);

/// Send a WebRTC signaling message (SDP offer/answer or ICE candidate) to a peer.
/// Rust routes it through the WSS relay to the target peer.
Future<void> webrtcSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
  required String connId,
}) => RustLib.instance.api.crateApiNetworkWebrtcSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
  connId: connId,
);

/// Notify Rust that a WebRTC file transfer completed (receiver side).
/// Rust will decrypt and process the received file.
Future<void> webrtcTransferComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  kind: kind,
  shardIndex: shardIndex,
);

/// Notify Rust that a WebRTC share-chunk transfer completed.
/// Distinct from `webrtc_transfer_complete` because share chunks need a
/// 32-bit chunk_index (a single share can have up to 4 billion chunks).
/// Routes into share_handler verify+decrypt+write path.
Future<void> webrtcShareChunkComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required int chunkIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcShareChunkComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  chunkIndex: chunkIndex,
);

/// Notify Rust that a WebRTC file send completed (sender side).
/// Rust cleans up the temp encrypted file.
Future<void> webrtcSendComplete({required String transferId}) => RustLib
    .instance
    .api
    .crateApiNetworkWebrtcSendComplete(transferId: transferId);

/// Notify Rust that a WebRTC transfer failed. Triggers WSS relay fallback.
Future<void> webrtcTransferFailed({
  required String transferId,
  required String peerId,
  required String error,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferFailed(
  transferId: transferId,
  peerId: peerId,
  error: error,
);

/// Send a voice call signaling message to a peer (Phase 5B).
Future<void> callSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkCallSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// Join a voice channel in a server (Phase 5C).
Future<void> voiceChannelJoin({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelJoin(
  serverId: serverId,
  channelId: channelId,
);

/// Leave a voice channel in a server (Phase 5C).
Future<void> voiceChannelLeave({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelLeave(
  serverId: serverId,
  channelId: channelId,
);

/// Send a voice channel signaling message (SDP/ICE) to a specific peer (Phase 5C).
Future<void> voiceChannelSendSignal({
  required String serverId,
  required String channelId,
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelSendSignal(
  serverId: serverId,
  channelId: channelId,
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// Report data channel keepalive RTT for gossip peer scoring.
Future<void> webrtcPingReport({required String peerId, required int rttMs}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPingReport(
      peerId: peerId,
      rttMs: rttMs,
    );

/// Notify Rust that a broadcast file was received via gossip data channel.
Future<void> webrtcBroadcastReceived({
  required String transferId,
  required String broadcastId,
  required int ttl,
  required String originPeerId,
  required String senderPeerId,
  required String tempPath,
  required BigInt totalSize,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcBroadcastReceived(
  transferId: transferId,
  broadcastId: broadcastId,
  ttl: ttl,
  originPeerId: originPeerId,
  senderPeerId: senderPeerId,
  tempPath: tempPath,
  totalSize: totalSize,
  kind: kind,
  shardIndex: shardIndex,
);

/// A discovered peer on the local network.
class DiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const DiscoveredPeer({required this.peerId, required this.addresses});

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

/// FFI-facing guest reaction.
class GuestReactionFfi {
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;

  const GuestReactionFfi({
    required this.emoji,
    required this.peerId,
    required this.addedAt,
  });

  @override
  int get hashCode => emoji.hashCode ^ peerId.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestReactionFfi &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt;
}

/// FFI-facing guest sync message.
class GuestSyncMessageFfi {
  final String senderId;
  final String text;
  final PlatformInt64 timestamp;
  final String? messageId;
  final String? signature;
  final String? publicKey;
  final PlatformInt64? editedAt;
  final String? replyTo;
  final PlatformInt64? hiddenAt;
  final List<GuestReactionFfi> reactions;

  const GuestSyncMessageFfi({
    required this.senderId,
    required this.text,
    required this.timestamp,
    this.messageId,
    this.signature,
    this.publicKey,
    this.editedAt,
    this.replyTo,
    this.hiddenAt,
    required this.reactions,
  });

  @override
  int get hashCode =>
      senderId.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      messageId.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      editedAt.hashCode ^
      replyTo.hashCode ^
      hiddenAt.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestSyncMessageFfi &&
          runtimeType == other.runtimeType &&
          senderId == other.senderId &&
          text == other.text &&
          timestamp == other.timestamp &&
          messageId == other.messageId &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          editedAt == other.editedAt &&
          replyTo == other.replyTo &&
          hiddenAt == other.hiddenAt &&
          reactions == other.reactions;
}

/// FFI-facing link preview for a URL embedded in a message.
///
/// Generated by the sender (fetch OG tags, download + compress thumbnail to
/// lossy WebP Q=50) and travels with the message. Receivers render the card
/// directly from these fields and NEVER make an HTTP request to the
/// previewed URL — this is a privacy property, not a cache optimization.
///
/// Phase 6.75 link previews. See HOLLOW_PLAN.md.
class LinkPreviewRef {
  /// The URL that was previewed.
  final String url;

  /// og:title or <title> fallback. Already truncated by the sender.
  final String title;

  /// og:description or meta description. Already truncated by the sender.
  final String description;

  /// Display domain parsed from the URL (e.g. "github.com").
  final String domain;

  /// og:site_name if present. Empty string = fall back to domain in UI.
  final String siteName;

  /// Base64-encoded lossy WebP thumbnail (Q=50, max dim 400px).
  /// None when no og:image was found or the image fetch failed.
  final String? thumbWebpB64;

  /// Thumbnail width after resize.
  final int? thumbW;

  /// Thumbnail height after resize.
  final int? thumbH;

  const LinkPreviewRef({
    required this.url,
    required this.title,
    required this.description,
    required this.domain,
    required this.siteName,
    this.thumbWebpB64,
    this.thumbW,
    this.thumbH,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      title.hashCode ^
      description.hashCode ^
      domain.hashCode ^
      siteName.hashCode ^
      thumbWebpB64.hashCode ^
      thumbW.hashCode ^
      thumbH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreviewRef &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          description == other.description &&
          domain == other.domain &&
          siteName == other.siteName &&
          thumbWebpB64 == other.thumbWebpB64 &&
          thumbW == other.thumbW &&
          thumbH == other.thumbH;
}

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.peerDiscovered({required DiscoveredPeer peer}) =
      NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.peerExpired({required String peerId}) =
      NetworkEvent_PeerExpired;
  const factory NetworkEvent.peerDisconnected({required String peerId}) =
      NetworkEvent_PeerDisconnected;
  const factory NetworkEvent.roomCleared() = NetworkEvent_RoomCleared;
  const factory NetworkEvent.listening({required String address}) =
      NetworkEvent_Listening;
  const factory NetworkEvent.messageReceived({
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.channelMessageReceived({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageReceived;
  const factory NetworkEvent.messageSent({
    required String toPeer,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_MessageSent;
  const factory NetworkEvent.channelMessageSent({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageSent;
  const factory NetworkEvent.messageSendFailed({
    required String toPeer,
    required String error,
  }) = NetworkEvent_MessageSendFailed;
  const factory NetworkEvent.sessionEstablished({required String peerId}) =
      NetworkEvent_SessionEstablished;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
  const factory NetworkEvent.serverCreated({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerCreated;
  const factory NetworkEvent.serverUpdated({required String serverId}) =
      NetworkEvent_ServerUpdated;
  const factory NetworkEvent.channelAdded({
    required String serverId,
    required String channelId,
    required String name,
    required String channelType,
  }) = NetworkEvent_ChannelAdded;
  const factory NetworkEvent.channelRemoved({
    required String serverId,
    required String channelId,
  }) = NetworkEvent_ChannelRemoved;
  const factory NetworkEvent.channelRenamed({
    required String serverId,
    required String channelId,
    required String newName,
  }) = NetworkEvent_ChannelRenamed;
  const factory NetworkEvent.serverDeleted({required String serverId}) =
      NetworkEvent_ServerDeleted;
  const factory NetworkEvent.memberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberJoined;
  const factory NetworkEvent.memberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberLeft;
  const factory NetworkEvent.syncCompleted({
    required String serverId,
    required int opsApplied,
  }) = NetworkEvent_SyncCompleted;
  const factory NetworkEvent.serverJoined({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerJoined;
  const factory NetworkEvent.serverJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_ServerJoinFailed;
  const factory NetworkEvent.messageSyncStarted({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MessageSyncStarted;
  const factory NetworkEvent.messageSyncCompleted({
    required String serverId,
    required int newMessageCount,
  }) = NetworkEvent_MessageSyncCompleted;
  const factory NetworkEvent.messageSyncFailed({
    required String serverId,
    required String error,
  }) = NetworkEvent_MessageSyncFailed;
  const factory NetworkEvent.messageSyncProgress({
    required String serverId,
    required String channelId,
    required int receivedCount,
    required int totalCount,
  }) = NetworkEvent_MessageSyncProgress;
  const factory NetworkEvent.roleChanged({
    required String serverId,
    required String peerId,
    required String newRole,
  }) = NetworkEvent_RoleChanged;
  const factory NetworkEvent.dmSyncCompleted({
    required String peerId,
    required int newMessageCount,
  }) = NetworkEvent_DmSyncCompleted;
  const factory NetworkEvent.profileUpdated({required String peerId}) =
      NetworkEvent_ProfileUpdated;
  const factory NetworkEvent.channelMessageEdited({
    required String serverId,
    required String channelId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageEdited;
  const factory NetworkEvent.dmMessageEdited({
    required String peerId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_DmMessageEdited;
  const factory NetworkEvent.channelMessageDeleted({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_ChannelMessageDeleted;
  const factory NetworkEvent.dmMessageDeleted({
    required String peerId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_DmMessageDeleted;
  const factory NetworkEvent.channelReactionAdded({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_ChannelReactionAdded;
  const factory NetworkEvent.dmReactionAdded({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_DmReactionAdded;
  const factory NetworkEvent.channelReactionRemoved({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_ChannelReactionRemoved;
  const factory NetworkEvent.dmReactionRemoved({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_DmReactionRemoved;
  const factory NetworkEvent.friendRequestReceived({required String peerId}) =
      NetworkEvent_FriendRequestReceived;
  const factory NetworkEvent.friendRequestAccepted({required String peerId}) =
      NetworkEvent_FriendRequestAccepted;
  const factory NetworkEvent.friendRequestRejected({required String peerId}) =
      NetworkEvent_FriendRequestRejected;
  const factory NetworkEvent.friendRemoved({required String peerId}) =
      NetworkEvent_FriendRemoved;
  const factory NetworkEvent.channelNotificationHint({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String messageId,
    required bool hasEveryone,
    required List<String> mentionedNames,
    required bool isReply,
  }) = NetworkEvent_ChannelNotificationHint;
  const factory NetworkEvent.typingStarted({
    required String peerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_TypingStarted;
  const factory NetworkEvent.peerStatusChanged({
    required String peerId,
    required String status,
  }) = NetworkEvent_PeerStatusChanged;
  const factory NetworkEvent.messagePinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessagePinned;
  const factory NetworkEvent.messageUnpinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessageUnpinned;
  const factory NetworkEvent.fileHeaderReceived({
    required String fileId,
    required String fileName,
    required BigInt sizeBytes,
    required bool isImage,
    int? width,
    int? height,
    required String messageId,
    required String senderId,
    required String serverId,
    required String channelId,

    /// Video thumbnail back-reference (Phase 6.75 video preview).
    /// Present when the received FileHeader is a thumbnail for a vault video.
    VideoThumbRef? videoThumb,

    /// Hidden Share back-reference for large files / progressive video streaming.
    String? shareRootHash,
    String? shareKeyHex,
  }) = NetworkEvent_FileHeaderReceived;
  const factory NetworkEvent.fileProgress({
    required String fileId,
    required int chunksReceived,
    required int totalChunks,
  }) = NetworkEvent_FileProgress;
  const factory NetworkEvent.fileCompleted({
    required String fileId,
    required String diskPath,
  }) = NetworkEvent_FileCompleted;
  const factory NetworkEvent.fileFailed({
    required String fileId,
    required String error,
  }) = NetworkEvent_FileFailed;
  const factory NetworkEvent.shardStored({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardStored;
  const factory NetworkEvent.shardStoreAckReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required bool success,
    required String error,
  }) = NetworkEvent_ShardStoreAckReceived;
  const factory NetworkEvent.shardStoreFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String targetPeer,
    required String error,
  }) = NetworkEvent_ShardStoreFailed;
  const factory NetworkEvent.shardDeleted({
    required String serverId,
    required String contentId,
  }) = NetworkEvent_ShardDeleted;
  const factory NetworkEvent.shardReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardReceived;
  const factory NetworkEvent.shardRequestFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String error,
  }) = NetworkEvent_ShardRequestFailed;
  const factory NetworkEvent.vaultUploadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultUploadProgress;
  const factory NetworkEvent.vaultUploadComplete({
    required String serverId,
    required String contentId,
    required String channelId,
  }) = NetworkEvent_VaultUploadComplete;
  const factory NetworkEvent.vaultUploadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultUploadFailed;
  const factory NetworkEvent.vaultDownloadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultDownloadProgress;
  const factory NetworkEvent.vaultDownloadComplete({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_VaultDownloadComplete;
  const factory NetworkEvent.vaultDownloadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultDownloadFailed;
  const factory NetworkEvent.rebalanceStarted({
    required String serverId,
    required int shardsToMove,
  }) = NetworkEvent_RebalanceStarted;
  const factory NetworkEvent.rebalanceProgress({
    required String serverId,
    required int moved,
    required int total,
  }) = NetworkEvent_RebalanceProgress;
  const factory NetworkEvent.rebalanceCompleted({required String serverId}) =
      NetworkEvent_RebalanceCompleted;
  const factory NetworkEvent.vaultUploadReplicationFallback({
    required String serverId,
    required String contentId,
    required BigInt online,
    required BigInt needed,
  }) = NetworkEvent_VaultUploadReplicationFallback;
  const factory NetworkEvent.keyExchangeStarted({required String peerId}) =
      NetworkEvent_KeyExchangeStarted;
  const factory NetworkEvent.keyExchangeProgress({
    required String peerId,
    required String stage,
  }) = NetworkEvent_KeyExchangeProgress;

  /// Forward incoming WebRTC signaling message to Dart.
  const factory NetworkEvent.webRtcSignal({
    required String peerId,
    required String signalType,
    required String payload,
    required String connId,
  }) = NetworkEvent_WebRtcSignal;

  /// Tell Dart to send a file over WebRTC data channel.
  const factory NetworkEvent.webRtcSendFile({
    required String peerId,
    required String transferId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required int chunkIndex,
  }) = NetworkEvent_WebRtcSendFile;

  /// Forward incoming voice call signaling message to Dart.
  const factory NetworkEvent.callSignal({
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_CallSignal;
  const factory NetworkEvent.voiceChannelJoined({
    required String serverId,
    required String channelId,
    required String peerId,
  }) = NetworkEvent_VoiceChannelJoined;
  const factory NetworkEvent.voiceChannelLeft({
    required String serverId,
    required String channelId,
    required String peerId,
  }) = NetworkEvent_VoiceChannelLeft;
  const factory NetworkEvent.voiceChannelSignal({
    required String serverId,
    required String channelId,
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_VoiceChannelSignal;
  const factory NetworkEvent.gossipConnect({required String peerId}) =
      NetworkEvent_GossipConnect;
  const factory NetworkEvent.gossipDisconnect({required String peerId}) =
      NetworkEvent_GossipDisconnect;
  const factory NetworkEvent.gossipRelayFile({
    required String broadcastId,
    required int ttl,
    required String originPeerId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required String excludePeerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_GossipRelayFile;
  const factory NetworkEvent.voiceChannelModeChanged({
    required String serverId,
    required String channelId,
    required String mode,
    required List<String> gossipNeighbors,
  }) = NetworkEvent_VoiceChannelModeChanged;

  /// MLS epoch changed — SFrame key for voice E2EE.
  const factory NetworkEvent.mlsEpochChanged({
    required String serverId,
    required BigInt epoch,
    required Uint8List sframeKey,
  }) = NetworkEvent_MlsEpochChanged;
  const factory NetworkEvent.recoveryPoolCreated({
    required String serverId,
    required String inviteLink,
  }) = NetworkEvent_RecoveryPoolCreated;
  const factory NetworkEvent.recoveryPoolJoined({required String serverId}) =
      NetworkEvent_RecoveryPoolJoined;
  const factory NetworkEvent.recoveryPoolJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_RecoveryPoolJoinFailed;
  const factory NetworkEvent.recoveryPoolMemberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberJoined;
  const factory NetworkEvent.recoveryPoolMemberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberLeft;
  const factory NetworkEvent.recoveryPoolStatus({
    required String serverId,
    required int totalFiles,
    required int reconstructable,
    required int partial,
    required int noShards,
    required double progressPct,
  }) = NetworkEvent_RecoveryPoolStatus;
  const factory NetworkEvent.recoveryPoolShardTransferred({
    required String serverId,
    required String contentId,
    required int shardIndex,
  }) = NetworkEvent_RecoveryPoolShardTransferred;
  const factory NetworkEvent.recoveryPoolFileRecovered({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_RecoveryPoolFileRecovered;
  const factory NetworkEvent.recoveryPoolStopped({required String serverId}) =
      NetworkEvent_RecoveryPoolStopped;
  const factory NetworkEvent.shareManifestReady({
    required String rootHash,
    required String fileName,
    required BigInt totalSize,
    required int chunkCount,
  }) = NetworkEvent_ShareManifestReady;
  const factory NetworkEvent.shareProgress({
    required String rootHash,
    required int chunksHave,
    required int chunksTotal,
    required int seeders,
    required int leechers,
    required BigInt bytesPerSec,
  }) = NetworkEvent_ShareProgress;
  const factory NetworkEvent.shareCompleted({
    required String rootHash,
    required String diskPath,
  }) = NetworkEvent_ShareCompleted;
  const factory NetworkEvent.shareFailed({
    required String rootHash,
    required String error,
  }) = NetworkEvent_ShareFailed;
  const factory NetworkEvent.shareSeedingChanged({
    required String rootHash,
    required bool seeding,
    required int seeders,
    required int leechers,
    required BigInt bytesUploaded,
  }) = NetworkEvent_ShareSeedingChanged;
  const factory NetworkEvent.shareCreated({
    required String rootHash,
    required String link,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreated;
  const factory NetworkEvent.shareCreatedHidden({
    required String rootHash,
    required String keyHex,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreatedHidden;
  const factory NetworkEvent.shareList({required List<ShareEntry> entries}) =
      NetworkEvent_ShareList;
  const factory NetworkEvent.shareNeedWebRtc({
    required String peerId,
    required bool hidden,
  }) = NetworkEvent_ShareNeedWebRtc;
  const factory NetworkEvent.licenseError({required String reason}) =
      NetworkEvent_LicenseError;
  const factory NetworkEvent.twitchJoinRejected({
    required String serverId,
    required String reason,
  }) = NetworkEvent_TwitchJoinRejected;
  const factory NetworkEvent.roomBudgetUpdate({
    required int joined,
    required int limit,
  }) = NetworkEvent_RoomBudgetUpdate;
  const factory NetworkEvent.roomCapHit({required String room}) =
      NetworkEvent_RoomCapHit;
  const factory NetworkEvent.publicChannelListReceived({
    required String serverId,
    required String serverName,
    required List<PublicChannelEntryFfi> channels,
    Uint8List? serverAvatar,
  }) = NetworkEvent_PublicChannelListReceived;
  const factory NetworkEvent.publicChannelSyncReceived({
    required String serverId,
    required String channelId,
    required List<GuestSyncMessageFfi> messages,
    required bool hasMore,
  }) = NetworkEvent_PublicChannelSyncReceived;
}

/// FFI-facing public channel entry for guest viewer.
class PublicChannelEntryFfi {
  final String channelId;
  final String name;
  final String? category;

  const PublicChannelEntryFfi({
    required this.channelId,
    required this.name,
    this.category,
  });

  @override
  int get hashCode => channelId.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicChannelEntryFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category;
}

/// Lightweight FFI mirror of node::types::ShareEntryRef.
class ShareEntry {
  final String rootHash;
  final String fileName;
  final BigInt totalSize;
  final int chunksHave;
  final int chunksTotal;
  final String state;
  final bool seeding;
  final String? diskPath;
  final BigInt bytesUploaded;
  final String shareLink;
  final PlatformInt64 createdAt;
  final String? serverId;
  final String? contextType;

  const ShareEntry({
    required this.rootHash,
    required this.fileName,
    required this.totalSize,
    required this.chunksHave,
    required this.chunksTotal,
    required this.state,
    required this.seeding,
    this.diskPath,
    required this.bytesUploaded,
    required this.shareLink,
    required this.createdAt,
    this.serverId,
    this.contextType,
  });

  @override
  int get hashCode =>
      rootHash.hashCode ^
      fileName.hashCode ^
      totalSize.hashCode ^
      chunksHave.hashCode ^
      chunksTotal.hashCode ^
      state.hashCode ^
      seeding.hashCode ^
      diskPath.hashCode ^
      bytesUploaded.hashCode ^
      shareLink.hashCode ^
      createdAt.hashCode ^
      serverId.hashCode ^
      contextType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareEntry &&
          runtimeType == other.runtimeType &&
          rootHash == other.rootHash &&
          fileName == other.fileName &&
          totalSize == other.totalSize &&
          chunksHave == other.chunksHave &&
          chunksTotal == other.chunksTotal &&
          state == other.state &&
          seeding == other.seeding &&
          diskPath == other.diskPath &&
          bytesUploaded == other.bytesUploaded &&
          shareLink == other.shareLink &&
          createdAt == other.createdAt &&
          serverId == other.serverId &&
          contextType == other.contextType;
}

/// FFI-facing video thumbnail back-reference.
///
/// When a `FileHeaderReceived` event carries this, the file is a thumbnail
/// image for an underlying video stored in the vault. Dart side uses these
/// fields to render the play button overlay, format duration/size badges,
/// and trigger `vault_download_file(cid)` when the user taps play.
///
/// Phase 6.75 video preview in chats. See HOLLOW_PLAN.md.
class VideoThumbRef {
  /// Vault content_id (sha256 of ciphertext) of the underlying video.
  final String cid;

  /// Original video file extension (mp4, webm, mkv, ...).
  final String ext;

  /// Original video file name (used as the default for the Save As dialog).
  final String name;

  /// Video size in bytes.
  final BigInt size;

  /// Video duration in milliseconds.
  final int durMs;

  const VideoThumbRef({
    required this.cid,
    required this.ext,
    required this.name,
    required this.size,
    required this.durMs,
  });

  @override
  int get hashCode =>
      cid.hashCode ^
      ext.hashCode ^
      name.hashCode ^
      size.hashCode ^
      durMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoThumbRef &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          ext == other.ext &&
          name == other.name &&
          size == other.size &&
          durMs == other.durMs;
}
