// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_forwarding_task`, `get_event_rx`, `get_node`, `get_runtime`, `to_ffi_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeState`

/// Start the libp2p node with mDNS peer discovery and E2EE.
/// Uses the persistent identity from disk.
/// Returns the local peer ID as a string.
Future<String> startNode() => RustLib.instance.api.crateApiNetworkStartNode();

/// Stream network events to Dart in real time.
/// Must be called after `start_node()`. Can only be called once per node lifetime.
Stream<NetworkEvent> watchNetworkEvents() =>
    RustLib.instance.api.crateApiNetworkWatchNetworkEvents();

/// Poll for the next network event. Returns None if no event is available.
/// Fallback for when streaming is not active.
Future<NetworkEvent?> pollNetworkEvent() =>
    RustLib.instance.api.crateApiNetworkPollNetworkEvent();

/// Get the local peer ID. Returns None if the node hasn't started.
Future<String?> getLocalPeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalPeerId();

/// Get the Olm identity fingerprint (Curve25519 base64).
/// Returns None if the node hasn't started.
Future<String?> getOlmFingerprint() =>
    RustLib.instance.api.crateApiNetworkGetOlmFingerprint();

/// Send a text message to a peer. The peer must be reachable (discovered via mDNS).
Future<void> sendMessage({
  required String peerId,
  required String text,
  required String messageId,
  String? replyToMid,
}) => RustLib.instance.api.crateApiNetworkSendMessage(
  peerId: peerId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
);

/// Send a text message to a server channel.
/// The message will be encrypted and sent to all connected server members.
Future<void> sendChannelMessage({
  required String serverId,
  required String channelId,
  required String text,
  required String messageId,
  String? replyToMid,
}) => RustLib.instance.api.crateApiNetworkSendChannelMessage(
  serverId: serverId,
  channelId: channelId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
);

/// Edit a channel message. Broadcasts the edit to all server members.
Future<void> editChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  newText: newText,
);

/// Edit a DM message. Sends the edit to the DM peer.
Future<void> editDmMessage({
  required String peerId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditDmMessage(
  peerId: peerId,
  messageId: messageId,
  newText: newText,
);

/// Delete (hide) a channel message. Broadcasts the deletion to all server members.
/// The message stays in the DB (Rat Files evidence) but is hidden from UI.
Future<void> deleteChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Delete (hide) a DM message. Sends the deletion to the DM peer.
Future<void> deleteDmMessage({
  required String peerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteDmMessage(
  peerId: peerId,
  messageId: messageId,
);

/// Add an emoji reaction to a channel message.
Future<void> addChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a channel message.
Future<void> removeChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Add an emoji reaction to a DM message.
Future<void> addDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a DM message.
Future<void> removeDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Send a friend request to a peer.
Future<void> sendFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkSendFriendRequest(peerId: peerId);

/// Accept a friend request from a peer.
Future<void> acceptFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkAcceptFriendRequest(peerId: peerId);

/// Reject a friend request from a peer.
Future<void> rejectFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRejectFriendRequest(peerId: peerId);

/// Remove a friend.
Future<void> removeFriend({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRemoveFriend(peerId: peerId);

/// Send a typing indicator to peers. Ephemeral, not stored.
/// For DMs: server_id = "", channel_id = peer ID.
/// For channels: server_id and channel_id as normal.
Future<void> sendTypingIndicator({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkSendTypingIndicator(
  serverId: serverId,
  channelId: channelId,
);

/// Request message sync for a specific channel from all connected server members.
/// Called when the user opens a channel to catch up on missed messages.
Future<void> requestChannelSync({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkRequestChannelSync(
  serverId: serverId,
  channelId: channelId,
);

/// Notify all connected peers that we're shutting down gracefully.
/// Call this before closing the app so peers can immediately update their state.
/// Update our display name, status, about me, and optionally avatar/banner —
/// saves to DB and broadcasts to all connected peers.
Future<void> updateProfile({
  required String displayName,
  required String status,
  required String aboutMe,
  Uint8List? avatarBytes,
  Uint8List? bannerBytes,
}) => RustLib.instance.api.crateApiNetworkUpdateProfile(
  displayName: displayName,
  status: status,
  aboutMe: aboutMe,
  avatarBytes: avatarBytes,
  bannerBytes: bannerBytes,
);

/// Process a raw image into avatar format (128x128 WebP). Returns processed bytes.
Future<Uint8List> processAvatar({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessAvatar(rawBytes: rawBytes);

/// Process a raw image into banner format (600x200 WebP). Returns processed bytes.
Future<Uint8List> processBanner({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessBanner(rawBytes: rawBytes);

Future<void> notifyShutdown() =>
    RustLib.instance.api.crateApiNetworkNotifyShutdown();

/// Join a room via the signaling service.
/// Registers our addresses and bootstraps from other peers in the room.
Future<void> joinRoom({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkJoinRoom(roomCode: roomCode);

/// Stop the running node.
Future<void> stopNode() => RustLib.instance.api.crateApiNetworkStopNode();

/// Send a file to a DM peer or server channel.
/// `peer_id`: target peer (for DMs, empty for channels).
/// `server_id` + `channel_id`: target channel (for servers, empty for DMs).
Future<void> sendFile({
  String? peerId,
  String? serverId,
  String? channelId,
  required String filePath,
  required String messageId,
  required String messageText,
}) => RustLib.instance.api.crateApiNetworkSendFile(
  peerId: peerId,
  serverId: serverId,
  channelId: channelId,
  filePath: filePath,
  messageId: messageId,
  messageText: messageText,
);

/// Request file chunks from a specific peer.
Future<void> requestFileFromPeer({
  required String fileId,
  required String peerId,
  required List<int> chunks,
}) => RustLib.instance.api.crateApiNetworkRequestFileFromPeer(
  fileId: fileId,
  peerId: peerId,
  chunks: chunks,
);

/// Convert a WebP image file to another format (PNG/JPEG).
/// Used for "Save As" functionality.
Future<Uint8List> convertImageFormat({
  required String sourcePath,
  required String targetFormat,
}) => RustLib.instance.api.crateApiNetworkConvertImageFormat(
  sourcePath: sourcePath,
  targetFormat: targetFormat,
);

/// Get the files directory path.
Future<String> getFilesDir() =>
    RustLib.instance.api.crateApiNetworkGetFilesDir();

/// A discovered peer on the local network.
class DiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const DiscoveredPeer({required this.peerId, required this.addresses});

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.peerDiscovered({required DiscoveredPeer peer}) =
      NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.peerExpired({required String peerId}) =
      NetworkEvent_PeerExpired;
  const factory NetworkEvent.peerDisconnected({required String peerId}) =
      NetworkEvent_PeerDisconnected;
  const factory NetworkEvent.roomCleared() = NetworkEvent_RoomCleared;
  const factory NetworkEvent.listening({required String address}) =
      NetworkEvent_Listening;
  const factory NetworkEvent.messageReceived({
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.channelMessageReceived({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
  }) = NetworkEvent_ChannelMessageReceived;
  const factory NetworkEvent.messageSent({required String toPeer}) =
      NetworkEvent_MessageSent;
  const factory NetworkEvent.messageSendFailed({
    required String toPeer,
    required String error,
  }) = NetworkEvent_MessageSendFailed;
  const factory NetworkEvent.sessionEstablished({required String peerId}) =
      NetworkEvent_SessionEstablished;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
  const factory NetworkEvent.serverCreated({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerCreated;
  const factory NetworkEvent.serverUpdated({required String serverId}) =
      NetworkEvent_ServerUpdated;
  const factory NetworkEvent.channelAdded({
    required String serverId,
    required String channelId,
    required String name,
  }) = NetworkEvent_ChannelAdded;
  const factory NetworkEvent.channelRemoved({
    required String serverId,
    required String channelId,
  }) = NetworkEvent_ChannelRemoved;
  const factory NetworkEvent.channelRenamed({
    required String serverId,
    required String channelId,
    required String newName,
  }) = NetworkEvent_ChannelRenamed;
  const factory NetworkEvent.serverDeleted({required String serverId}) =
      NetworkEvent_ServerDeleted;
  const factory NetworkEvent.memberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberJoined;
  const factory NetworkEvent.memberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberLeft;
  const factory NetworkEvent.syncCompleted({
    required String serverId,
    required int opsApplied,
  }) = NetworkEvent_SyncCompleted;
  const factory NetworkEvent.serverJoined({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerJoined;
  const factory NetworkEvent.messageSyncStarted({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MessageSyncStarted;
  const factory NetworkEvent.messageSyncCompleted({
    required String serverId,
    required int newMessageCount,
  }) = NetworkEvent_MessageSyncCompleted;
  const factory NetworkEvent.messageSyncFailed({
    required String serverId,
    required String error,
  }) = NetworkEvent_MessageSyncFailed;
  const factory NetworkEvent.messageSyncProgress({
    required String serverId,
    required String channelId,
    required int receivedCount,
    required int totalCount,
  }) = NetworkEvent_MessageSyncProgress;
  const factory NetworkEvent.roleChanged({
    required String serverId,
    required String peerId,
    required String newRole,
  }) = NetworkEvent_RoleChanged;
  const factory NetworkEvent.dmSyncCompleted({
    required String peerId,
    required int newMessageCount,
  }) = NetworkEvent_DmSyncCompleted;
  const factory NetworkEvent.profileUpdated({required String peerId}) =
      NetworkEvent_ProfileUpdated;
  const factory NetworkEvent.channelMessageEdited({
    required String serverId,
    required String channelId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
  }) = NetworkEvent_ChannelMessageEdited;
  const factory NetworkEvent.dmMessageEdited({
    required String peerId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
  }) = NetworkEvent_DmMessageEdited;
  const factory NetworkEvent.channelMessageDeleted({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_ChannelMessageDeleted;
  const factory NetworkEvent.dmMessageDeleted({
    required String peerId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_DmMessageDeleted;
  const factory NetworkEvent.channelReactionAdded({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_ChannelReactionAdded;
  const factory NetworkEvent.dmReactionAdded({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_DmReactionAdded;
  const factory NetworkEvent.channelReactionRemoved({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_ChannelReactionRemoved;
  const factory NetworkEvent.dmReactionRemoved({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_DmReactionRemoved;
  const factory NetworkEvent.friendRequestReceived({required String peerId}) =
      NetworkEvent_FriendRequestReceived;
  const factory NetworkEvent.friendRequestAccepted({required String peerId}) =
      NetworkEvent_FriendRequestAccepted;
  const factory NetworkEvent.friendRequestRejected({required String peerId}) =
      NetworkEvent_FriendRequestRejected;
  const factory NetworkEvent.friendRemoved({required String peerId}) =
      NetworkEvent_FriendRemoved;
  const factory NetworkEvent.typingStarted({
    required String peerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_TypingStarted;
  const factory NetworkEvent.messagePinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessagePinned;
  const factory NetworkEvent.messageUnpinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessageUnpinned;
  const factory NetworkEvent.fileHeaderReceived({
    required String fileId,
    required String fileName,
    required BigInt sizeBytes,
    required bool isImage,
    int? width,
    int? height,
    required String messageId,
    required String senderId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_FileHeaderReceived;
  const factory NetworkEvent.fileProgress({
    required String fileId,
    required int chunksReceived,
    required int totalChunks,
  }) = NetworkEvent_FileProgress;
  const factory NetworkEvent.fileCompleted({
    required String fileId,
    required String diskPath,
  }) = NetworkEvent_FileCompleted;
  const factory NetworkEvent.fileFailed({
    required String fileId,
    required String error,
  }) = NetworkEvent_FileFailed;
  const factory NetworkEvent.shardStored({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardStored;
  const factory NetworkEvent.shardStoreAckReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required bool success,
    required String error,
  }) = NetworkEvent_ShardStoreAckReceived;
  const factory NetworkEvent.shardStoreFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String targetPeer,
    required String error,
  }) = NetworkEvent_ShardStoreFailed;
  const factory NetworkEvent.shardDeleted({
    required String serverId,
    required String contentId,
  }) = NetworkEvent_ShardDeleted;
  const factory NetworkEvent.shardReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardReceived;
  const factory NetworkEvent.shardRequestFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String error,
  }) = NetworkEvent_ShardRequestFailed;
  const factory NetworkEvent.vaultUploadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultUploadProgress;
  const factory NetworkEvent.vaultUploadComplete({
    required String serverId,
    required String contentId,
    required String channelId,
  }) = NetworkEvent_VaultUploadComplete;
  const factory NetworkEvent.vaultUploadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultUploadFailed;
  const factory NetworkEvent.vaultDownloadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultDownloadProgress;
  const factory NetworkEvent.vaultDownloadComplete({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_VaultDownloadComplete;
  const factory NetworkEvent.vaultDownloadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultDownloadFailed;
  const factory NetworkEvent.rebalanceStarted({
    required String serverId,
    required int shardsToMove,
  }) = NetworkEvent_RebalanceStarted;
  const factory NetworkEvent.rebalanceProgress({
    required String serverId,
    required int moved,
    required int total,
  }) = NetworkEvent_RebalanceProgress;
  const factory NetworkEvent.rebalanceCompleted({required String serverId}) =
      NetworkEvent_RebalanceCompleted;
  const factory NetworkEvent.connectionAttemptStarted({
    required String peerId,
    required String method,
  }) = NetworkEvent_ConnectionAttemptStarted;
  const factory NetworkEvent.connectionAttemptFailed({
    required String peerId,
    required String method,
    required String reason,
  }) = NetworkEvent_ConnectionAttemptFailed;
  const factory NetworkEvent.keyExchangeStarted({required String peerId}) =
      NetworkEvent_KeyExchangeStarted;
  const factory NetworkEvent.keyExchangeProgress({
    required String peerId,
    required String stage,
  }) = NetworkEvent_KeyExchangeProgress;
  const factory NetworkEvent.relayStatusChanged({required String status}) =
      NetworkEvent_RelayStatusChanged;
}
