// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Pure helper: parse a hollow://share/... link into its root_hash + key.
/// No I/O, no network — safe to call from any thread.
Future<ShareLinkInfo> shareDecodeLink({required String link}) =>
    RustLib.instance.api.crateApiShareShareDecodeLink(link: link);

/// Build a manifest from a local file, encrypt every chunk with a fresh
/// random key, persist the share row, write the encrypted stream to
/// `~/.hollow/shares/{root_hash}.{ext}`, join the swarm room, start seeding.
/// Emits NetworkEvent::ShareCreated on success or ShareFailed on error.
Future<void> shareCreateFromFile({required String sourcePath}) => RustLib
    .instance
    .api
    .crateApiShareShareCreateFromFile(sourcePath: sourcePath);

/// Decode a share link, persist a placeholder row, join the swarm room, and
/// queue a manifest request. Emits NetworkEvent::ShareManifestReady when the
/// manifest arrives (or ShareFailed on error).
Future<void> shareOpenLink({required String link}) =>
    RustLib.instance.api.crateApiShareShareOpenLink(link: link);

/// Begin downloading after ShareManifestReady.
/// When `sequential` is true, chunks are fetched in order (0, 1, 2, ...)
/// instead of rarest-first. Used for progressive video streaming.
Future<void> shareStartDownload({
  required String rootHash,
  required String saveDir,
  required String link,
  required bool sequential,
}) => RustLib.instance.api.crateApiShareShareStartDownload(
  rootHash: rootHash,
  saveDir: saveDir,
  link: link,
  sequential: sequential,
);

/// Stop an in-flight download. Keeps the partial file + bitmap so the next
/// share_start_download resumes from where we left off.
Future<void> shareCancel({required String rootHash}) =>
    RustLib.instance.api.crateApiShareShareCancel(rootHash: rootHash);

/// Toggle seeding for a completed share.
Future<void> shareSetSeeding({
  required String rootHash,
  required bool seeding,
}) => RustLib.instance.api.crateApiShareShareSetSeeding(
  rootHash: rootHash,
  seeding: seeding,
);

/// Drop a share entry. If `delete_file = true`, also unlinks the on-disk file
/// (and any partial download).
Future<void> shareRemove({
  required String rootHash,
  required bool deleteFile,
}) => RustLib.instance.api.crateApiShareShareRemove(
  rootHash: rootHash,
  deleteFile: deleteFile,
);

/// Start a hidden Share download from raw root_hash + key (no link URL parsing).
/// Used by the receiver when a FileHeader carries a ShareRef.
/// Joins the swarm room, fetches manifest, and starts sequential download.
Future<void> shareStartFromRef({
  required String rootHash,
  required String keyHex,
  required String saveDir,
  required bool sequential,
}) => RustLib.instance.api.crateApiShareShareStartFromRef(
  rootHash: rootHash,
  keyHex: keyHex,
  saveDir: saveDir,
  sequential: sequential,
);

/// Enumerate persisted shares. Result returned via NetworkEvent::ShareList.
Future<void> shareList() => RustLib.instance.api.crateApiShareShareList();

class ShareLinkInfo {
  final String rootHash;
  final String roomId;

  const ShareLinkInfo({required this.rootHash, required this.roomId});

  @override
  int get hashCode => rootHash.hashCode ^ roomId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareLinkInfo &&
          runtimeType == other.runtimeType &&
          rootHash == other.rootHash &&
          roomId == other.roomId;
}
