// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_db_key`, `get_store`, `stored_file_to_ffi`

/// Open the encrypted message database. Must be called after identity is loaded.
/// Typically called once at app start (after `load_or_create_identity`).
Future<void> openMessageStore() =>
    RustLib.instance.api.crateApiStorageOpenMessageStore();

/// Save a message to the local database.
Future<PlatformInt64> saveMessage({
  required String peerId,
  required String text,
  required bool isMine,
  required PlatformInt64 timestamp,
  String? signature,
  String? publicKey,
}) => RustLib.instance.api.crateApiStorageSaveMessage(
  peerId: peerId,
  text: text,
  isMine: isMine,
  timestamp: timestamp,
  signature: signature,
  publicKey: publicKey,
);

/// Load recent messages for a peer from the local database.
/// Returns messages ordered oldest-first, up to `limit`.
Future<List<StoredMessage>> loadMessages({
  required String peerId,
  required int limit,
}) => RustLib.instance.api.crateApiStorageLoadMessages(
  peerId: peerId,
  limit: limit,
);

/// Get a profile for a specific peer (or ourselves). Returns None if no profile stored.
Future<UserProfile?> getProfile({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetProfile(peerId: peerId);

/// Get all stored profiles (for populating the profile cache on startup).
Future<List<UserProfile>> getAllProfiles() =>
    RustLib.instance.api.crateApiStorageGetAllProfiles();

/// Save a key-value setting to the local database.
Future<void> saveSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiStorageSaveSetting(key: key, value: value);

/// Load a setting by key. Returns None if not set.
Future<String?> loadSetting({required String key}) =>
    RustLib.instance.api.crateApiStorageLoadSetting(key: key);

/// Load all friends, optionally filtered by status.
Future<List<FriendFfi>> loadFriends({String? status}) =>
    RustLib.instance.api.crateApiStorageLoadFriends(status: status);

/// A single reaction on a message, returned to Dart.
/// Search channel messages by text.
Future<List<StoredChannelMessage>> searchChannelMessages({
  required String serverId,
  required String channelId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiStorageSearchChannelMessages(
  serverId: serverId,
  channelId: channelId,
  query: query,
  limit: limit,
);

/// Search DM messages by text.
Future<List<StoredMessage>> searchDmMessages({
  required String peerId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiStorageSearchDmMessages(
  peerId: peerId,
  query: query,
  limit: limit,
);

/// Load all reactions for a list of message IDs.
/// Returns reactions grouped by message_id for efficient bulk loading.
Future<List<StoredReaction>> loadReactions({
  required List<String> messageIds,
}) => RustLib.instance.api.crateApiStorageLoadReactions(messageIds: messageIds);

/// Save a channel message to the local database.
Future<PlatformInt64> saveChannelMessage({
  required String serverId,
  required String channelId,
  required String senderId,
  required String text,
  required bool isMine,
  required PlatformInt64 timestamp,
  String? signature,
  String? publicKey,
}) => RustLib.instance.api.crateApiStorageSaveChannelMessage(
  serverId: serverId,
  channelId: channelId,
  senderId: senderId,
  text: text,
  isMine: isMine,
  timestamp: timestamp,
  signature: signature,
  publicKey: publicKey,
);

/// Load recent channel messages from the local database.
/// Returns messages ordered oldest-first, up to `limit`.
Future<List<StoredChannelMessage>> loadChannelMessages({
  required String serverId,
  required String channelId,
  required int limit,
}) => RustLib.instance.api.crateApiStorageLoadChannelMessages(
  serverId: serverId,
  channelId: channelId,
  limit: limit,
);

/// Get file metadata by file ID.
Future<StoredFileInfo?> getFileMetadata({required String fileId}) =>
    RustLib.instance.api.crateApiStorageGetFileMetadata(fileId: fileId);

/// Get the vault content_id linked to a file by its file_id.
/// Returns None if no vault content_id is set (e.g. DM files, <6 member files).
Future<String?> getContentIdForFile({required String fileId}) =>
    RustLib.instance.api.crateApiStorageGetContentIdForFile(fileId: fileId);

/// Get all files attached to a message.
Future<List<StoredFileInfo>> getFilesForMessage({required String messageId}) =>
    RustLib.instance.api.crateApiStorageGetFilesForMessage(
      messageId: messageId,
    );

/// Get all incomplete files (for sync resume).
Future<List<StoredFileInfo>> getIncompleteFiles() =>
    RustLib.instance.api.crateApiStorageGetIncompleteFiles();

/// Get file_ids from messages that have no completed file on disk.
/// Used to find files that need downloading after message sync.
Future<List<String>> getMissingFileIds() =>
    RustLib.instance.api.crateApiStorageGetMissingFileIds();

/// Get file IDs for missing images in a specific server.
/// Used for late-joiner image sync in 6+ member servers.
Future<List<String>> getMissingImageFileIdsForServer({
  required String serverId,
}) => RustLib.instance.api.crateApiStorageGetMissingImageFileIdsForServer(
  serverId: serverId,
);

/// A friend entry returned to Dart.
class FriendFfi {
  final String peerId;
  final String status;
  final String direction;
  final PlatformInt64 requestedAt;
  final PlatformInt64 updatedAt;

  const FriendFfi({
    required this.peerId,
    required this.status,
    required this.direction,
    required this.requestedAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      status.hashCode ^
      direction.hashCode ^
      requestedAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          status == other.status &&
          direction == other.direction &&
          requestedAt == other.requestedAt &&
          updatedAt == other.updatedAt;
}

/// A channel message returned to Dart from the local database.
class StoredChannelMessage {
  final PlatformInt64 id;
  final String serverId;
  final String channelId;
  final String senderId;
  final String text;
  final bool isMine;
  final PlatformInt64 timestamp;
  final String? signature;
  final String? publicKey;
  final String? messageId;
  final PlatformInt64? editedAt;
  final PlatformInt64? hiddenAt;
  final String? replyToMid;
  final String? fileId;

  const StoredChannelMessage({
    required this.id,
    required this.serverId,
    required this.channelId,
    required this.senderId,
    required this.text,
    required this.isMine,
    required this.timestamp,
    this.signature,
    this.publicKey,
    this.messageId,
    this.editedAt,
    this.hiddenAt,
    this.replyToMid,
    this.fileId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serverId.hashCode ^
      channelId.hashCode ^
      senderId.hashCode ^
      text.hashCode ^
      isMine.hashCode ^
      timestamp.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      messageId.hashCode ^
      editedAt.hashCode ^
      hiddenAt.hashCode ^
      replyToMid.hashCode ^
      fileId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredChannelMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serverId == other.serverId &&
          channelId == other.channelId &&
          senderId == other.senderId &&
          text == other.text &&
          isMine == other.isMine &&
          timestamp == other.timestamp &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          messageId == other.messageId &&
          editedAt == other.editedAt &&
          hiddenAt == other.hiddenAt &&
          replyToMid == other.replyToMid &&
          fileId == other.fileId;
}

/// File metadata returned to Dart.
class StoredFileInfo {
  final String fileId;
  final String fileName;
  final String fileExt;
  final String mimeType;
  final BigInt sizeBytes;
  final int chunkCount;
  final int chunksReceived;
  final bool isImage;
  final int? width;
  final int? height;
  final String? messageId;
  final String contextType;
  final String contextId;
  final String senderId;
  final bool isMine;
  final PlatformInt64 createdAt;
  final PlatformInt64? completedAt;
  final String? diskPath;

  const StoredFileInfo({
    required this.fileId,
    required this.fileName,
    required this.fileExt,
    required this.mimeType,
    required this.sizeBytes,
    required this.chunkCount,
    required this.chunksReceived,
    required this.isImage,
    this.width,
    this.height,
    this.messageId,
    required this.contextType,
    required this.contextId,
    required this.senderId,
    required this.isMine,
    required this.createdAt,
    this.completedAt,
    this.diskPath,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      fileName.hashCode ^
      fileExt.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      chunkCount.hashCode ^
      chunksReceived.hashCode ^
      isImage.hashCode ^
      width.hashCode ^
      height.hashCode ^
      messageId.hashCode ^
      contextType.hashCode ^
      contextId.hashCode ^
      senderId.hashCode ^
      isMine.hashCode ^
      createdAt.hashCode ^
      completedAt.hashCode ^
      diskPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredFileInfo &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          fileName == other.fileName &&
          fileExt == other.fileExt &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          chunkCount == other.chunkCount &&
          chunksReceived == other.chunksReceived &&
          isImage == other.isImage &&
          width == other.width &&
          height == other.height &&
          messageId == other.messageId &&
          contextType == other.contextType &&
          contextId == other.contextId &&
          senderId == other.senderId &&
          isMine == other.isMine &&
          createdAt == other.createdAt &&
          completedAt == other.completedAt &&
          diskPath == other.diskPath;
}

/// A message returned to Dart from the local database.
class StoredMessage {
  final PlatformInt64 id;
  final String peerId;
  final String text;
  final bool isMine;
  final PlatformInt64 timestamp;
  final String? signature;
  final String? publicKey;
  final String? messageId;
  final PlatformInt64? editedAt;
  final PlatformInt64? hiddenAt;
  final String? replyToMid;
  final String? fileId;

  const StoredMessage({
    required this.id,
    required this.peerId,
    required this.text,
    required this.isMine,
    required this.timestamp,
    this.signature,
    this.publicKey,
    this.messageId,
    this.editedAt,
    this.hiddenAt,
    this.replyToMid,
    this.fileId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peerId.hashCode ^
      text.hashCode ^
      isMine.hashCode ^
      timestamp.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      messageId.hashCode ^
      editedAt.hashCode ^
      hiddenAt.hashCode ^
      replyToMid.hashCode ^
      fileId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peerId == other.peerId &&
          text == other.text &&
          isMine == other.isMine &&
          timestamp == other.timestamp &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          messageId == other.messageId &&
          editedAt == other.editedAt &&
          hiddenAt == other.hiddenAt &&
          replyToMid == other.replyToMid &&
          fileId == other.fileId;
}

class StoredReaction {
  final String messageId;
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;

  const StoredReaction({
    required this.messageId,
    required this.emoji,
    required this.peerId,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^ emoji.hashCode ^ peerId.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredReaction &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt;
}

/// A user profile returned to Dart.
class UserProfile {
  final String peerId;
  final String displayName;
  final String status;
  final String aboutMe;
  final PlatformInt64 updatedAt;
  final Uint8List? avatarBytes;
  final Uint8List? bannerBytes;

  const UserProfile({
    required this.peerId,
    required this.displayName,
    required this.status,
    required this.aboutMe,
    required this.updatedAt,
    this.avatarBytes,
    this.bannerBytes,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      aboutMe.hashCode ^
      updatedAt.hashCode ^
      avatarBytes.hashCode ^
      bannerBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          status == other.status &&
          aboutMe == other.aboutMe &&
          updatedAt == other.updatedAt &&
          avatarBytes == other.avatarBytes &&
          bannerBytes == other.bannerBytes;
}
