// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_db_key`, `get_store`

/// Open the encrypted message database. Must be called after identity is loaded.
/// Typically called once at app start (after `load_or_create_identity`).
Future<void> openMessageStore() =>
    RustLib.instance.api.crateApiStorageOpenMessageStore();

/// Save a message to the local database.
Future<PlatformInt64> saveMessage({
  required String peerId,
  required String text,
  required bool isMine,
  required PlatformInt64 timestamp,
}) => RustLib.instance.api.crateApiStorageSaveMessage(
  peerId: peerId,
  text: text,
  isMine: isMine,
  timestamp: timestamp,
);

/// Load recent messages for a peer from the local database.
/// Returns messages ordered oldest-first, up to `limit`.
Future<List<StoredMessage>> loadMessages({
  required String peerId,
  required int limit,
}) => RustLib.instance.api.crateApiStorageLoadMessages(
  peerId: peerId,
  limit: limit,
);

/// A message returned to Dart from the local database.
class StoredMessage {
  final PlatformInt64 id;
  final String peerId;
  final String text;
  final bool isMine;
  final PlatformInt64 timestamp;

  const StoredMessage({
    required this.id,
    required this.peerId,
    required this.text,
    required this.isMine,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peerId.hashCode ^
      text.hashCode ^
      isMine.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peerId == other.peerId &&
          text == other.text &&
          isMine == other.isMine &&
          timestamp == other.timestamp;
}
