// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_token_cache`, `load_tw_setting`, `save_tw_setting`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedToken`

Future<TwitchDeviceFlowResult> twitchStartDeviceFlow() =>
    RustLib.instance.api.crateApiTwitchTwitchStartDeviceFlow();

Future<String> twitchPollForToken({
  required String deviceCode,
  required BigInt intervalSecs,
}) => RustLib.instance.api.crateApiTwitchTwitchPollForToken(
  deviceCode: deviceCode,
  intervalSecs: intervalSecs,
);

Future<bool> twitchEnsureToken() =>
    RustLib.instance.api.crateApiTwitchTwitchEnsureToken();

Future<String> twitchGenerateProof({required String broadcasterId}) => RustLib
    .instance
    .api
    .crateApiTwitchTwitchGenerateProof(broadcasterId: broadcasterId);

Future<void> twitchDisconnect() =>
    RustLib.instance.api.crateApiTwitchTwitchDisconnect();

Future<bool> twitchIsConnected() =>
    RustLib.instance.api.crateApiTwitchTwitchIsConnected();

Future<String?> twitchGetUserId() =>
    RustLib.instance.api.crateApiTwitchTwitchGetUserId();

class TwitchDeviceFlowResult {
  final String userCode;
  final String verificationUri;
  final String deviceCode;
  final BigInt intervalSecs;

  const TwitchDeviceFlowResult({
    required this.userCode,
    required this.verificationUri,
    required this.deviceCode,
    required this.intervalSecs,
  });

  @override
  int get hashCode =>
      userCode.hashCode ^
      verificationUri.hashCode ^
      deviceCode.hashCode ^
      intervalSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TwitchDeviceFlowResult &&
          runtimeType == other.runtimeType &&
          userCode == other.userCode &&
          verificationUri == other.verificationUri &&
          deviceCode == other.deviceCode &&
          intervalSecs == other.intervalSecs;
}
